"""first commit

Revision ID: af8cbbc3c9eb
Revises: 
Create Date: 2023-12-30 08:19:14.401901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af8cbbc3c9eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('CustomerCategories',
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('min_spending', sa.DECIMAL(precision=18, scale=0), nullable=True),
    sa.Column('discount_percentage', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('Employees',
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('citizen_id', sa.String(length=255), nullable=True),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.INTEGER(), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citizen_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('PurchaseOrders',
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('import_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('discount', mysql.INTEGER(), nullable=True),
    sa.Column('vat', mysql.INTEGER(), nullable=True),
    sa.Column('original_price', sa.String(length=255), nullable=True),
    sa.Column('final_price', sa.String(length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('Suppliers',
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('Customers',
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('total_spending', sa.DECIMAL(precision=30, scale=0), nullable=True),
    sa.Column('customer_category_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_category_id'], ['CustomerCategories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_name')
    )
    op.create_table('Products',
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_code', sa.String(length=255), nullable=True),
    sa.Column('promotion_price', sa.DECIMAL(precision=18, scale=0), nullable=True),
    sa.Column('category_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('supplier_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('manufacture_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('stock_quantity', mysql.INTEGER(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['Suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('SupplierPurchaseOrders',
    sa.Column('supplier_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('import_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['PurchaseOrders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['Suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Images',
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Orders',
    sa.Column('order_code', sa.String(length=255), nullable=True),
    sa.Column('customer_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('original_price', sa.String(length=255), nullable=True),
    sa.Column('discount', mysql.INTEGER(), nullable=True),
    sa.Column('final_price', sa.String(length=255), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), nullable=True),
    sa.Column('status', mysql.INTEGER(), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_code')
    )
    op.create_table('ProductPurchaseOrders',
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('import_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['PurchaseOrders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_classifications',
    sa.Column('item_classification_name', sa.String(length=255), nullable=True),
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_classification_name')
    )
    op.create_table('OrderDetails',
    sa.Column('order_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('total_with_discount', sa.DECIMAL(precision=18, scale=0), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_item_classifications',
    sa.Column('sub_item_classification_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=18, scale=0), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('item_classification_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_classification_id'], ['item_classifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_item_classifications')
    op.drop_table('OrderDetails')
    op.drop_table('item_classifications')
    op.drop_table('ProductPurchaseOrders')
    op.drop_table('Orders')
    op.drop_table('Images')
    op.drop_table('SupplierPurchaseOrders')
    op.drop_table('Products')
    op.drop_table('Customers')
    op.drop_table('Suppliers')
    op.drop_table('PurchaseOrders')
    op.drop_table('Employees')
    op.drop_table('CustomerCategories')
    op.drop_table('Categories')
    # ### end Alembic commands ###
