"""first commit

Revision ID: c0dee4178732
Revises: 
Create Date: 2023-12-18 11:27:02.212008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c0dee4178732'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('imports',
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('import_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('discount', mysql.INTEGER(), nullable=True),
    sa.Column('vat', mysql.INTEGER(), nullable=True),
    sa.Column('original_price', sa.String(length=255), nullable=True),
    sa.Column('final_price', sa.String(length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('member_ranks',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('spending', sa.DECIMAL(precision=18, scale=0), nullable=True),
    sa.Column('discount', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('suppliers',
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('account', sa.String(length=255), nullable=True),
    sa.Column('total_spending', sa.DECIMAL(precision=30, scale=0), nullable=True),
    sa.Column('rank_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rank_id'], ['member_ranks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_code', sa.String(length=255), nullable=True),
    sa.Column('promotion_price', sa.DECIMAL(precision=18, scale=0), nullable=True),
    sa.Column('category_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('supplier_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('manufacture_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('supplier_imports',
    sa.Column('supplier_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('import_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_classifications',
    sa.Column('item_classification_name', sa.String(length=255), nullable=True),
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_classification_name')
    )
    op.create_table('orders',
    sa.Column('order_code', sa.String(length=255), nullable=True),
    sa.Column('customer_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('original_price', sa.String(length=255), nullable=True),
    sa.Column('discount', mysql.INTEGER(), nullable=True),
    sa.Column('final_price', sa.String(length=255), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), nullable=True),
    sa.Column('status', mysql.INTEGER(), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_code')
    )
    op.create_table('product_imports',
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('import_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_details',
    sa.Column('order_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('total_price', sa.DECIMAL(precision=18, scale=0), nullable=True),
    sa.Column('quantity_order', mysql.INTEGER(), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_item_classifications',
    sa.Column('sub_item_classification_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=18, scale=0), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('item_classification_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_classification_id'], ['item_classifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_item_classifications')
    op.drop_table('order_details')
    op.drop_table('product_imports')
    op.drop_table('orders')
    op.drop_table('item_classifications')
    op.drop_table('images')
    op.drop_table('supplier_imports')
    op.drop_table('products')
    op.drop_table('customers')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('member_ranks')
    op.drop_table('imports')
    op.drop_table('categories')
    # ### end Alembic commands ###
