# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/admin/import_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1112, 885)
        Form.setStyleSheet("QLineEdit, QPlainTextEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"      height: 48px;\n"
"    font-weight: 600;\n"
"    text-align: left;\n"
"    font-size: 14px;\n"
"\n"
"    font-weight: 600;\n"
"    background: #fff;\n"
"    padding: 0 16px;\n"
"}\n"
"#tableUserContainer{\n"
"    border: none;\n"
"    border-radius:  4px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"       padding: 0 16px;\n"
"    vertical-align: middle;\n"
"    height: 50px;\n"
"    border-bottom: 1px solid #ddd;    \n"
"    border-right: 1px solid #ddd;\n"
"    cursor: pointer;\n"
"}\n"
"    QScrollBar:vertical\n"
"    {\n"
"        background-color: #fff;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: #cdd3d6;         /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"#scrollArea_2, #verticalLayout_6, #userDialogForm, #scrollAreaWidgetContents_2, #widget{\n"
"    background: #fff;\n"
"}\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"#dialog_product_title{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus, QPlainTextEdit:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"#userDialogForm QLabel{\n"
"    color: #000;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#userDialogForm  QLineEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-height: 36px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"QHBoxLayout QLabel{\n"
"    background: red;\n"
"}\n"
"\n"
"#btn_save_import{\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"#btn_add_product_category{\n"
"    min-height: 42px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"#btn_save_import:hover{\n"
"        background: #0062cc;\n"
"}\n"
"\n"
"\n"
"#btn_cancel_import{\n"
"    background: #ebebeb;\n"
"    outline: none;\n"
"    border: 1px solid #e0e0e0;\n"
"    min-height: 36px;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btn_cancel_import:hover{\n"
"    background: #f4f5f8;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"      height: 48px;\n"
"    font-weight: 600;\n"
"    text-align: left;\n"
"    font-size: 14px;\n"
"\n"
"    font-weight: 600;\n"
"    background: #fff;\n"
"    padding: 0 16px;\n"
"}\n"
"#tableUserContainer{\n"
"    border: none;\n"
"    border-radius:  4px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"       padding: 0 16px;\n"
"    vertical-align: middle;\n"
"    height: 50px;\n"
"    border-bottom: 1px solid #ddd;\n"
"    border-right: 1px solid #ddd;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"#stackedWidget{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#userDialogForm QLabel{\n"
"    color: #000;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#userDialogForm  QLineEdit, #userDialogForm QComboBox, QSpinBox{\n"
"    border: 1px solid #e0e5e9;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QLineEdit, QComboxBox,QSpinBox{\n"
"    border: 1px solid #e0e5e9;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus, #centralwidget QComboBox:focus, QSpinBox:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"#btnCancelUser,#btn_image_product, #btn_manufacture_date_product{\n"
"    background: #ebebeb;\n"
"    outline: none;\n"
"    border: 1px solid #e0e0e0;\n"
"    min-height: 36px;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btnCancelUser:hover, #btn_image_product:hover{\n"
"    background: #f4f5f8;\n"
"}\n"
"\n"
"#btnUser{\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-height: 36px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btnUser:hover{\n"
"        background: #0062cc;\n"
"}\n"
"\n"
"#footerUserContainer{\n"
"     background-color: #fbfbfe;\n"
"    padding: 12px 24px;\n"
"    border-top: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#backBtn{\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"#dialog_import_title{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#popupHeader{\n"
"    height: 60px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"#code_import_container, #delivery_date_container, #import_date_container, #supplier_import_container, #vat_import_container, #discount_import_container{\n"
"        border-bottom: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#widget_4{\n"
"    border-top: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#userDialogForm{\n"
"        border-radius: 4px;\n"
"        border: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"\n"
"\n"
"#userDialogFormSubContainer{\n"
"    background: #e9e9e9;\n"
"    border-radius: 4px;\n"
"}\n"
" #formInput_4 QLabel {\n"
"    margin-top: 10px;\n"
"}\n"
"QHBoxLayout QLabel{\n"
"    background: red;\n"
"}\n"
"\n"
"#label_product_1, #labelUserName, #labelPassword, #labelConfirm{\n"
"    margin-top:30px;\n"
"}\n"
"\n"
"QPushButton, QComboBox{\n"
"    min-width: 80px;\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#error_user, #error_quantity, #error_manufacture_date, #error_description, #error_address, #error_phone, #error_name, #error_code{\n"
"    padding-top: 8px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"#addUserBtn, #btn_add_category, #btn_add_product{\n"
"        width:  100px;\n"
"        background: #2979ff;\n"
"        color: #fff;\n"
"}\n"
"\n"
"#addUserBtn:hover{\n"
"    background: #1a73e8;\n"
"}\n"
"\n"
"#addUserBtn QLabel{\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#search_btn_2{\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer QLineEdit, #searchBoxContainer_2 QLineEdit, #search_input_category_2, #search_input_product_2{\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer, #searchBoxContainer_3, #searchBoxContainer_5{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#searchBoxContainer_2{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#headerAdmin{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#change_btn{\n"
"    max-width: 20px !important;\n"
"}\n"
"\n"
"#change_btn:hover{\n"
"    background: #ddd;\n"
"}\n"
"\n"
"#btn_add_order_user, #search_btn_5,  #search_btn_2, #back_btn_category, #search_btn_category_2, #search_btn_product_2, #btn_image_product, #btn_manufacture_date_product, #back_btn_import, #search_btn_order_2{\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"\n"
"#search_input_5{\n"
"    padding: 0;\n"
"    padding-left: 10px\n"
"}\n"
"\n"
"#customers_btn_2, #products_btn_2, #orders_btn_2, #dashboard_btn_2,#home_btn_2,#user_btn_2, #category_btn_2{\n"
"    text-align: left;\n"
"}\n"
"\n"
"#label_required_4, #label_required_3, #label_required_2, #label_required_1{\n"
"    text-align: right;\n"
"}\n"
"\n"
"#btn_image_product{\n"
"    min-height:  40px;\n"
"    min-width: 64px;\n"
"}\n"
"\n"
"QPlainTextEdit{\n"
"    min-height: 82px;\n"
"}\n"
"\n"
"#table_product_order:item{\n"
"    border:none;\n"
"}\n"
"\n"
"#table_product_order_container{\n"
"    border: 1px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 34px;\n"
"    min-width: 34px;\n"
"    max-width: 34px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"#total_price_main{\n"
"    margin-right: 20px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.popupHeader = QtWidgets.QWidget(self.widget)
        self.popupHeader.setMinimumSize(QtCore.QSize(0, 60))
        self.popupHeader.setObjectName("popupHeader")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.popupHeader)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.back_btn_import = QtWidgets.QPushButton(self.popupHeader)
        self.back_btn_import.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn_import.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/icon/back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn_import.setIcon(icon)
        self.back_btn_import.setObjectName("back_btn_import")
        self.horizontalLayout_7.addWidget(self.back_btn_import)
        self.dialog_import_title = QtWidgets.QLabel(self.popupHeader)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(True)
        self.dialog_import_title.setFont(font)
        self.dialog_import_title.setObjectName("dialog_import_title")
        self.horizontalLayout_7.addWidget(self.dialog_import_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addWidget(self.popupHeader)
        self.widget_9 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.userDialogForm = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userDialogForm.sizePolicy().hasHeightForWidth())
        self.userDialogForm.setSizePolicy(sizePolicy)
        self.userDialogForm.setMinimumSize(QtCore.QSize(900, 300))
        self.userDialogForm.setObjectName("userDialogForm")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.userDialogForm)
        self.verticalLayout_10.setContentsMargins(50, 20, 50, 30)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.userDialogForm)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 783, 1822))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.code_import_container = QtWidgets.QWidget(self.widget_2)
        self.code_import_container.setMinimumSize(QtCore.QSize(0, 105))
        self.code_import_container.setMaximumSize(QtCore.QSize(16777215, 105))
        self.code_import_container.setObjectName("code_import_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.code_import_container)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_27 = QtWidgets.QWidget(self.code_import_container)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.formInput_11 = QtWidgets.QHBoxLayout()
        self.formInput_11.setContentsMargins(-1, 0, -1, -1)
        self.formInput_11.setSpacing(0)
        self.formInput_11.setObjectName("formInput_11")
        self.label_product_2 = QtWidgets.QWidget(self.widget_27)
        self.label_product_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_2.setObjectName("label_product_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.label_product_2)
        self.horizontalLayout_9.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.label_product_2)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.label_required_5 = QtWidgets.QLabel(self.label_product_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_5.sizePolicy().hasHeightForWidth())
        self.label_required_5.setSizePolicy(sizePolicy)
        self.label_required_5.setText("")
        self.label_required_5.setObjectName("label_required_5")
        self.horizontalLayout_9.addWidget(self.label_required_5)
        self.formInput_11.addWidget(self.label_product_2, 0, QtCore.Qt.AlignTop)
        self.widget_28 = QtWidgets.QWidget(self.widget_27)
        self.widget_28.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_28)
        self.verticalLayout_20.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.code_le = QtWidgets.QLineEdit(self.widget_28)
        self.code_le.setMinimumSize(QtCore.QSize(222, 46))
        self.code_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.code_le.setFont(font)
        self.code_le.setText("")
        self.code_le.setClearButtonEnabled(True)
        self.code_le.setObjectName("code_le")
        self.verticalLayout_20.addWidget(self.code_le)
        self.error_code = QtWidgets.QLabel(self.widget_28)
        self.error_code.setText("")
        self.error_code.setObjectName("error_code")
        self.verticalLayout_20.addWidget(self.error_code)
        self.formInput_11.addWidget(self.widget_28, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_29.addLayout(self.formInput_11)
        self.verticalLayout_3.addWidget(self.widget_27)
        self.verticalLayout_21.addWidget(self.code_import_container)
        self.supplier_import_container = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.supplier_import_container.sizePolicy().hasHeightForWidth())
        self.supplier_import_container.setSizePolicy(sizePolicy)
        self.supplier_import_container.setMinimumSize(QtCore.QSize(0, 0))
        self.supplier_import_container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.supplier_import_container.setObjectName("supplier_import_container")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.supplier_import_container)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_14 = QtWidgets.QWidget(self.supplier_import_container)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.formInput_5 = QtWidgets.QHBoxLayout()
        self.formInput_5.setContentsMargins(-1, 0, -1, -1)
        self.formInput_5.setSpacing(0)
        self.formInput_5.setObjectName("formInput_5")
        self.label_product_1 = QtWidgets.QWidget(self.widget_14)
        self.label_product_1.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_1.setObjectName("label_product_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.label_product_1)
        self.horizontalLayout_2.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.label_product_1)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_required_1 = QtWidgets.QLabel(self.label_product_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_1.sizePolicy().hasHeightForWidth())
        self.label_required_1.setSizePolicy(sizePolicy)
        self.label_required_1.setText("")
        self.label_required_1.setObjectName("label_required_1")
        self.horizontalLayout_2.addWidget(self.label_required_1)
        self.formInput_5.addWidget(self.label_product_1, 0, QtCore.Qt.AlignTop)
        self.widget_15 = QtWidgets.QWidget(self.widget_14)
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_16.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_29 = QtWidgets.QWidget(self.widget_15)
        self.widget_29.setObjectName("widget_29")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_29)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_30.setSpacing(15)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.supplier_le = QtWidgets.QComboBox(self.widget_29)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(-1)
        self.supplier_le.setFont(font)
        self.supplier_le.setMouseTracking(False)
        self.supplier_le.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.supplier_le.setEditable(True)
        self.supplier_le.setObjectName("supplier_le")
        self.horizontalLayout_30.addWidget(self.supplier_le)
        self.btn_add_order_user = QtWidgets.QPushButton(self.widget_29)
        self.btn_add_order_user.setMinimumSize(QtCore.QSize(54, 40))
        self.btn_add_order_user.setMaximumSize(QtCore.QSize(46, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.btn_add_order_user.setFont(font)
        self.btn_add_order_user.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_add_order_user.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/resources/icon/plus-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_order_user.setIcon(icon1)
        self.btn_add_order_user.setIconSize(QtCore.QSize(24, 24))
        self.btn_add_order_user.setObjectName("btn_add_order_user")
        self.horizontalLayout_30.addWidget(self.btn_add_order_user)
        self.verticalLayout_22.addLayout(self.horizontalLayout_30)
        self.verticalLayout_16.addWidget(self.widget_29)
        self.error_supplier = QtWidgets.QLabel(self.widget_15)
        self.error_supplier.setText("")
        self.error_supplier.setObjectName("error_supplier")
        self.verticalLayout_16.addWidget(self.error_supplier)
        self.formInput_5.addWidget(self.widget_15)
        self.horizontalLayout_14.addLayout(self.formInput_5)
        self.verticalLayout_12.addWidget(self.widget_14)
        self.table_info_user_container = QtWidgets.QWidget(self.supplier_import_container)
        self.table_info_user_container.setMinimumSize(QtCore.QSize(0, 400))
        self.table_info_user_container.setObjectName("table_info_user_container")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.table_info_user_container)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.table_supplier = QtWidgets.QTableWidget(self.table_info_user_container)
        self.table_supplier.setMinimumSize(QtCore.QSize(0, 400))
        self.table_supplier.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_supplier.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.table_supplier.setShowGrid(True)
        self.table_supplier.setGridStyle(QtCore.Qt.CustomDashLine)
        self.table_supplier.setRowCount(0)
        self.table_supplier.setObjectName("table_supplier")
        self.table_supplier.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        item.setFont(font)
        self.table_supplier.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        item.setFont(font)
        self.table_supplier.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        item.setFont(font)
        self.table_supplier.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        item.setFont(font)
        self.table_supplier.setHorizontalHeaderItem(3, item)
        self.table_supplier.horizontalHeader().setDefaultSectionSize(230)
        self.table_supplier.horizontalHeader().setStretchLastSection(True)
        self.table_supplier.verticalHeader().setVisible(False)
        self.table_supplier.verticalHeader().setHighlightSections(False)
        self.verticalLayout_18.addWidget(self.table_supplier)
        self.verticalLayout_12.addWidget(self.table_info_user_container)
        self.verticalLayout_21.addWidget(self.supplier_import_container)
        self.import_date_container = QtWidgets.QWidget(self.widget_2)
        self.import_date_container.setMinimumSize(QtCore.QSize(0, 105))
        self.import_date_container.setMaximumSize(QtCore.QSize(16777215, 105))
        self.import_date_container.setObjectName("import_date_container")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.import_date_container)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget_32 = QtWidgets.QWidget(self.import_date_container)
        self.widget_32.setObjectName("widget_32")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.widget_32)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.formInput_13 = QtWidgets.QHBoxLayout()
        self.formInput_13.setContentsMargins(-1, 0, -1, -1)
        self.formInput_13.setSpacing(0)
        self.formInput_13.setObjectName("formInput_13")
        self.label_product_4 = QtWidgets.QWidget(self.widget_32)
        self.label_product_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_4.setObjectName("label_product_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.label_product_4)
        self.horizontalLayout_15.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.label_product_4)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        self.label_required_7 = QtWidgets.QLabel(self.label_product_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_7.sizePolicy().hasHeightForWidth())
        self.label_required_7.setSizePolicy(sizePolicy)
        self.label_required_7.setText("")
        self.label_required_7.setObjectName("label_required_7")
        self.horizontalLayout_15.addWidget(self.label_required_7)
        self.formInput_13.addWidget(self.label_product_4, 0, QtCore.Qt.AlignTop)
        self.widget_33 = QtWidgets.QWidget(self.widget_32)
        self.widget_33.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_33.setObjectName("widget_33")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_33)
        self.verticalLayout_24.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.import_date_le = QtWidgets.QLineEdit(self.widget_33)
        self.import_date_le.setMinimumSize(QtCore.QSize(222, 46))
        self.import_date_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.import_date_le.setFont(font)
        self.import_date_le.setText("")
        self.import_date_le.setReadOnly(True)
        self.import_date_le.setClearButtonEnabled(False)
        self.import_date_le.setObjectName("import_date_le")
        self.verticalLayout_24.addWidget(self.import_date_le)
        self.error_order_code_2 = QtWidgets.QLabel(self.widget_33)
        self.error_order_code_2.setText("")
        self.error_order_code_2.setObjectName("error_order_code_2")
        self.verticalLayout_24.addWidget(self.error_order_code_2)
        self.formInput_13.addWidget(self.widget_33, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_32.addLayout(self.formInput_13)
        self.verticalLayout_19.addWidget(self.widget_32)
        self.verticalLayout_21.addWidget(self.import_date_container)
        self.delivery_date_container = QtWidgets.QWidget(self.widget_2)
        self.delivery_date_container.setMinimumSize(QtCore.QSize(0, 105))
        self.delivery_date_container.setMaximumSize(QtCore.QSize(16777215, 105))
        self.delivery_date_container.setObjectName("delivery_date_container")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.delivery_date_container)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.widget_34 = QtWidgets.QWidget(self.delivery_date_container)
        self.widget_34.setObjectName("widget_34")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.widget_34)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.formInput_14 = QtWidgets.QHBoxLayout()
        self.formInput_14.setContentsMargins(-1, 0, -1, -1)
        self.formInput_14.setSpacing(0)
        self.formInput_14.setObjectName("formInput_14")
        self.label_product_5 = QtWidgets.QWidget(self.widget_34)
        self.label_product_5.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_5.setObjectName("label_product_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.label_product_5)
        self.horizontalLayout_16.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.label_product_5)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_16.addWidget(self.label_7)
        self.label_required_8 = QtWidgets.QLabel(self.label_product_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_8.sizePolicy().hasHeightForWidth())
        self.label_required_8.setSizePolicy(sizePolicy)
        self.label_required_8.setText("")
        self.label_required_8.setObjectName("label_required_8")
        self.horizontalLayout_16.addWidget(self.label_required_8)
        self.formInput_14.addWidget(self.label_product_5, 0, QtCore.Qt.AlignTop)
        self.widget_35 = QtWidgets.QWidget(self.widget_34)
        self.widget_35.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_35.setObjectName("widget_35")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.widget_35)
        self.verticalLayout_25.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.delivery_date_le = QtWidgets.QLineEdit(self.widget_35)
        self.delivery_date_le.setMinimumSize(QtCore.QSize(222, 46))
        self.delivery_date_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.delivery_date_le.setFont(font)
        self.delivery_date_le.setText("")
        self.delivery_date_le.setReadOnly(True)
        self.delivery_date_le.setClearButtonEnabled(False)
        self.delivery_date_le.setObjectName("delivery_date_le")
        self.verticalLayout_25.addWidget(self.delivery_date_le)
        self.error_order_code_3 = QtWidgets.QLabel(self.widget_35)
        self.error_order_code_3.setText("")
        self.error_order_code_3.setObjectName("error_order_code_3")
        self.verticalLayout_25.addWidget(self.error_order_code_3)
        self.formInput_14.addWidget(self.widget_35, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_33.addLayout(self.formInput_14)
        self.verticalLayout_26.addWidget(self.widget_34)
        self.verticalLayout_21.addWidget(self.delivery_date_container)
        self.discount_import_container = QtWidgets.QWidget(self.widget_2)
        self.discount_import_container.setObjectName("discount_import_container")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.discount_import_container)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.widget_38 = QtWidgets.QWidget(self.discount_import_container)
        self.widget_38.setMinimumSize(QtCore.QSize(0, 105))
        self.widget_38.setMaximumSize(QtCore.QSize(16777215, 105))
        self.widget_38.setObjectName("widget_38")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.widget_38)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setSpacing(0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.formInput_16 = QtWidgets.QHBoxLayout()
        self.formInput_16.setContentsMargins(-1, 0, -1, -1)
        self.formInput_16.setSpacing(0)
        self.formInput_16.setObjectName("formInput_16")
        self.label_product_7 = QtWidgets.QWidget(self.widget_38)
        self.label_product_7.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_7.setObjectName("label_product_7")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.label_product_7)
        self.horizontalLayout_18.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_9 = QtWidgets.QLabel(self.label_product_7)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_18.addWidget(self.label_9)
        self.label_required_9 = QtWidgets.QLabel(self.label_product_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_9.sizePolicy().hasHeightForWidth())
        self.label_required_9.setSizePolicy(sizePolicy)
        self.label_required_9.setText("")
        self.label_required_9.setObjectName("label_required_9")
        self.horizontalLayout_18.addWidget(self.label_required_9)
        self.formInput_16.addWidget(self.label_product_7, 0, QtCore.Qt.AlignTop)
        self.widget_39 = QtWidgets.QWidget(self.widget_38)
        self.widget_39.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_39.setObjectName("widget_39")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.widget_39)
        self.verticalLayout_29.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.discount_le = QtWidgets.QSpinBox(self.widget_39)
        self.discount_le.setMaximum(100)
        self.discount_le.setObjectName("discount_le")
        self.verticalLayout_29.addWidget(self.discount_le)
        self.error_order_code_5 = QtWidgets.QLabel(self.widget_39)
        self.error_order_code_5.setText("")
        self.error_order_code_5.setObjectName("error_order_code_5")
        self.verticalLayout_29.addWidget(self.error_order_code_5)
        self.formInput_16.addWidget(self.widget_39, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_35.addLayout(self.formInput_16)
        self.verticalLayout_30.addWidget(self.widget_38)
        self.verticalLayout_21.addWidget(self.discount_import_container)
        self.vat_import_container = QtWidgets.QWidget(self.widget_2)
        self.vat_import_container.setMinimumSize(QtCore.QSize(0, 105))
        self.vat_import_container.setMaximumSize(QtCore.QSize(16777215, 105))
        self.vat_import_container.setObjectName("vat_import_container")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.vat_import_container)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.widget_36 = QtWidgets.QWidget(self.vat_import_container)
        self.widget_36.setObjectName("widget_36")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.widget_36)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.formInput_15 = QtWidgets.QHBoxLayout()
        self.formInput_15.setContentsMargins(-1, 0, -1, -1)
        self.formInput_15.setSpacing(0)
        self.formInput_15.setObjectName("formInput_15")
        self.label_product_6 = QtWidgets.QWidget(self.widget_36)
        self.label_product_6.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_6.setObjectName("label_product_6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.label_product_6)
        self.horizontalLayout_17.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.label_product_6)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_17.addWidget(self.label_8, 0, QtCore.Qt.AlignTop)
        self.formInput_15.addWidget(self.label_product_6)
        self.widget_37 = QtWidgets.QWidget(self.widget_36)
        self.widget_37.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_37.setObjectName("widget_37")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.widget_37)
        self.verticalLayout_27.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.vat_le = QtWidgets.QSpinBox(self.widget_37)
        self.vat_le.setMaximum(100)
        self.vat_le.setObjectName("vat_le")
        self.verticalLayout_27.addWidget(self.vat_le)
        self.error_order_code_4 = QtWidgets.QLabel(self.widget_37)
        self.error_order_code_4.setText("")
        self.error_order_code_4.setObjectName("error_order_code_4")
        self.verticalLayout_27.addWidget(self.error_order_code_4)
        self.formInput_15.addWidget(self.widget_37, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_34.addLayout(self.formInput_15)
        self.verticalLayout_28.addWidget(self.widget_36)
        self.verticalLayout_21.addWidget(self.vat_import_container)
        self.widget_20 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_27.setContentsMargins(0, 15, 0, 15)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.widget_21 = QtWidgets.QWidget(self.widget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_21.sizePolicy().hasHeightForWidth())
        self.widget_21.setSizePolicy(sizePolicy)
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.widget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setContentsMargins(20, 20, 20, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_s = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_s.sizePolicy().hasHeightForWidth())
        self.widget_s.setSizePolicy(sizePolicy)
        self.widget_s.setObjectName("widget_s")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_s)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(20)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_8 = QtWidgets.QWidget(self.widget_s)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.search_box_product_order = QtWidgets.QComboBox(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_box_product_order.sizePolicy().hasHeightForWidth())
        self.search_box_product_order.setSizePolicy(sizePolicy)
        self.search_box_product_order.setMinimumSize(QtCore.QSize(222, 46))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.search_box_product_order.setFont(font)
        self.search_box_product_order.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_box_product_order.setFocusPolicy(QtCore.Qt.NoFocus)
        self.search_box_product_order.setEditable(True)
        self.search_box_product_order.setCurrentText("")
        self.search_box_product_order.setIconSize(QtCore.QSize(30, 30))
        self.search_box_product_order.setFrame(True)
        self.search_box_product_order.setObjectName("search_box_product_order")
        self.horizontalLayout_10.addWidget(self.search_box_product_order)
        spacerItem2 = QtWidgets.QSpacerItem(308, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_13.addWidget(self.widget_8)
        self.table_product_order_container = QtWidgets.QWidget(self.widget_s)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_product_order_container.sizePolicy().hasHeightForWidth())
        self.table_product_order_container.setSizePolicy(sizePolicy)
        self.table_product_order_container.setMinimumSize(QtCore.QSize(0, 0))
        self.table_product_order_container.setMaximumSize(QtCore.QSize(16777215, 500))
        self.table_product_order_container.setObjectName("table_product_order_container")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.table_product_order_container)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tableUserContainer = QtWidgets.QFrame(self.table_product_order_container)
        self.tableUserContainer.setMinimumSize(QtCore.QSize(0, 400))
        self.tableUserContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableUserContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableUserContainer.setObjectName("tableUserContainer")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tableUserContainer)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.table_product_import = QtWidgets.QTableWidget(self.tableUserContainer)
        self.table_product_import.setEnabled(True)
        self.table_product_import.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.table_product_import.setFocusPolicy(QtCore.Qt.NoFocus)
        self.table_product_import.setAcceptDrops(False)
        self.table_product_import.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_product_import.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.table_product_import.setProperty("showDropIndicator", True)
        self.table_product_import.setDragEnabled(False)
        self.table_product_import.setAlternatingRowColors(False)
        self.table_product_import.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_product_import.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_product_import.setIconSize(QtCore.QSize(0, 0))
        self.table_product_import.setTextElideMode(QtCore.Qt.ElideNone)
        self.table_product_import.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.table_product_import.setShowGrid(True)
        self.table_product_import.setGridStyle(QtCore.Qt.CustomDashLine)
        self.table_product_import.setCornerButtonEnabled(False)
        self.table_product_import.setRowCount(0)
        self.table_product_import.setColumnCount(4)
        self.table_product_import.setObjectName("table_product_import")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        item.setFont(font)
        self.table_product_import.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        item.setFont(font)
        self.table_product_import.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        item.setFont(font)
        self.table_product_import.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product_import.setHorizontalHeaderItem(3, item)
        self.table_product_import.horizontalHeader().setVisible(True)
        self.table_product_import.horizontalHeader().setCascadingSectionResizes(False)
        self.table_product_import.horizontalHeader().setDefaultSectionSize(165)
        self.table_product_import.horizontalHeader().setHighlightSections(True)
        self.table_product_import.horizontalHeader().setMinimumSectionSize(57)
        self.table_product_import.horizontalHeader().setSortIndicatorShown(False)
        self.table_product_import.horizontalHeader().setStretchLastSection(True)
        self.table_product_import.verticalHeader().setVisible(False)
        self.table_product_import.verticalHeader().setCascadingSectionResizes(False)
        self.table_product_import.verticalHeader().setDefaultSectionSize(40)
        self.table_product_import.verticalHeader().setHighlightSections(True)
        self.table_product_import.verticalHeader().setMinimumSectionSize(21)
        self.gridLayout_9.addWidget(self.table_product_import, 0, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.tableUserContainer)
        self.verticalLayout_13.addWidget(self.table_product_order_container)
        self.error_product = QtWidgets.QLabel(self.widget_s)
        self.error_product.setText("")
        self.error_product.setObjectName("error_product")
        self.verticalLayout_13.addWidget(self.error_product)
        self.widget_56 = QtWidgets.QWidget(self.widget_s)
        self.widget_56.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_56.setObjectName("widget_56")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_56)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_57 = QtWidgets.QWidget(self.widget_56)
        self.widget_57.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_57.setObjectName("widget_57")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_57)
        self.horizontalLayout_5.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ds = QtWidgets.QHBoxLayout()
        self.ds.setContentsMargins(0, -1, -1, -1)
        self.ds.setSpacing(0)
        self.ds.setObjectName("ds")
        spacerItem3 = QtWidgets.QSpacerItem(308, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ds.addItem(spacerItem3)
        self.widget_i = QtWidgets.QWidget(self.widget_57)
        self.widget_i.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_i.setMaximumSize(QtCore.QSize(300, 50))
        self.widget_i.setObjectName("widget_i")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_i)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_import = QtWidgets.QWidget(self.widget_i)
        self.widget_import.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_import.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_import.setObjectName("widget_import")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_import)
        self.horizontalLayout_4.setContentsMargins(0, 0, 30, 5)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_i = QtWidgets.QHBoxLayout()
        self.horizontalLayout_i.setSpacing(0)
        self.horizontalLayout_i.setObjectName("horizontalLayout_i")
        self.label = QtWidgets.QLabel(self.widget_import)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_i.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_i.addItem(spacerItem4)
        self.total_price_main = QtWidgets.QLabel(self.widget_import)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setStrikeOut(True)
        self.total_price_main.setFont(font)
        self.total_price_main.setText("")
        self.total_price_main.setTextFormat(QtCore.Qt.AutoText)
        self.total_price_main.setObjectName("total_price_main")
        self.horizontalLayout_i.addWidget(self.total_price_main)
        self.total_quantity_product_order = QtWidgets.QLabel(self.widget_import)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.total_quantity_product_order.setFont(font)
        self.total_quantity_product_order.setObjectName("total_quantity_product_order")
        self.horizontalLayout_i.addWidget(self.total_quantity_product_order)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_i)
        self.verticalLayout_15.addWidget(self.widget_import)
        self.ds.addWidget(self.widget_i)
        self.horizontalLayout_5.addLayout(self.ds)
        self.horizontalLayout_6.addWidget(self.widget_57)
        self.verticalLayout_13.addWidget(self.widget_56)
        self.verticalLayout_8.addWidget(self.widget_s)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout_27.addWidget(self.widget_21)
        self.verticalLayout_21.addWidget(self.widget_20)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_30 = QtWidgets.QWidget(self.widget_5)
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.widget_30)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.formInput_12 = QtWidgets.QHBoxLayout()
        self.formInput_12.setContentsMargins(-1, 0, -1, -1)
        self.formInput_12.setSpacing(0)
        self.formInput_12.setObjectName("formInput_12")
        self.label_product_3 = QtWidgets.QWidget(self.widget_30)
        self.label_product_3.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_3.setObjectName("label_product_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.label_product_3)
        self.horizontalLayout_13.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.label_product_3)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.label_required_6 = QtWidgets.QLabel(self.label_product_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_6.sizePolicy().hasHeightForWidth())
        self.label_required_6.setSizePolicy(sizePolicy)
        self.label_required_6.setText("")
        self.label_required_6.setObjectName("label_required_6")
        self.horizontalLayout_13.addWidget(self.label_required_6)
        self.formInput_12.addWidget(self.label_product_3, 0, QtCore.Qt.AlignTop)
        self.widget_31 = QtWidgets.QWidget(self.widget_30)
        self.widget_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_31.setObjectName("widget_31")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_31)
        self.verticalLayout_23.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.status = QtWidgets.QComboBox(self.widget_31)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.verticalLayout_23.addWidget(self.status)
        self.error_order = QtWidgets.QLabel(self.widget_31)
        self.error_order.setText("")
        self.error_order.setObjectName("error_order")
        self.verticalLayout_23.addWidget(self.error_order)
        self.formInput_12.addWidget(self.widget_31, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_31.addLayout(self.formInput_12)
        self.verticalLayout_17.addWidget(self.widget_30)
        self.verticalLayout_21.addWidget(self.widget_5)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.userDialogFormSubContainer = QtWidgets.QWidget(self.userDialogForm)
        self.userDialogFormSubContainer.setObjectName("userDialogFormSubContainer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.userDialogFormSubContainer)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 10, 20, 10)
        self.horizontalLayout_19.setSpacing(10)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.btn_cancel_import = QtWidgets.QPushButton(self.userDialogFormSubContainer)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.btn_cancel_import.setFont(font)
        self.btn_cancel_import.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel_import.setObjectName("btn_cancel_import")
        self.horizontalLayout_19.addWidget(self.btn_cancel_import)
        self.btn_save_import = QtWidgets.QPushButton(self.userDialogFormSubContainer)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.btn_save_import.setFont(font)
        self.btn_save_import.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_import.setObjectName("btn_save_import")
        self.horizontalLayout_19.addWidget(self.btn_save_import)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.verticalLayout_6.addWidget(self.userDialogFormSubContainer)
        self.verticalLayout_10.addLayout(self.verticalLayout_6)
        self.horizontalLayout_11.addWidget(self.userDialogForm)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7.addWidget(self.widget_9)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dialog_import_title.setText(_translate("Form", "Thêm mới chứng từ"))
        self.label_4.setText(_translate("Form", "Mã chứng từ"))
        self.code_le.setPlaceholderText(_translate("Form", "Mã chứng từ"))
        self.label_2.setText(_translate("Form", "Nhà cung cấp"))
        self.supplier_le.setPlaceholderText(_translate("Form", "Tìm theo tên, số điện thoại,..."))
        item = self.table_supplier.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mã đơn vị cung cấp"))
        item = self.table_supplier.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tên đơn vị cung cấp"))
        item = self.table_supplier.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Số điện thoại"))
        item = self.table_supplier.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Thao tác"))
        self.label_6.setText(_translate("Form", "Ngày nhập"))
        self.import_date_le.setPlaceholderText(_translate("Form", "Ngày nhập"))
        self.label_7.setText(_translate("Form", "Ngày giao"))
        self.delivery_date_le.setPlaceholderText(_translate("Form", "Ngày giao"))
        self.label_9.setText(_translate("Form", "Chiết khấu"))
        self.label_8.setText(_translate("Form", "Thuế VAT"))
        self.groupBox.setTitle(_translate("Form", "Sản phẩm"))
        self.search_box_product_order.setPlaceholderText(_translate("Form", "Tìm kiếm theo mã, tên sản phẩm"))
        self.table_product_import.setSortingEnabled(False)
        item = self.table_product_import.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Thông tin sản phẩm"))
        item = self.table_product_import.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Đơn giá"))
        item = self.table_product_import.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Số lượng"))
        item = self.table_product_import.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Thành tiền"))
        self.label.setText(_translate("Form", "Tổng tiền:"))
        self.total_quantity_product_order.setText(_translate("Form", "0đ"))
        self.label_5.setText(_translate("Form", "Trạng thái đơn hàng"))
        self.status.setItemText(0, _translate("Form", "Chờ xử lý"))
        self.status.setItemText(1, _translate("Form", "Hoàn thành"))
        self.status.setItemText(2, _translate("Form", "Thất bại"))
        self.btn_cancel_import.setText(_translate("Form", "Hủy"))
        self.btn_save_import.setText(_translate("Form", "Lưu"))
import ui.resource_rc
