# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/admin/product_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(949, 962)
        Form.setStyleSheet("QLineEdit, QPlainTextEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"    QScrollBar:vertical\n"
"    {\n"
"        background-color: #fff;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: #cdd3d6;         /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"#scrollArea_2, #verticalLayout_6, #userDialogForm, #scrollAreaWidgetContents_2, #widget{\n"
"    background: #fff;\n"
"}\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"#dialog_product_title{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus, QPlainTextEdit:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"#userDialogForm QLabel{\n"
"    color: #000;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#userDialogForm  QLineEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-height: 36px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"QHBoxLayout QLabel{\n"
"    background: red;\n"
"}\n"
"\n"
"#btn_save_product{\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"#btn_add_product_category{\n"
"    min-height: 42px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"#btn_save_product:hover{\n"
"        background: #0062cc;\n"
"}\n"
"\n"
"\n"
"#btn_cancel_product{\n"
"    background: #ebebeb;\n"
"    outline: none;\n"
"    border: 1px solid #e0e0e0;\n"
"    min-height: 36px;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btn_cancel_product:hover{\n"
"    background: #f4f5f8;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"      height: 48px;\n"
"    font-weight: 600;\n"
"    text-align: left;\n"
"    font-size: 14px;\n"
"\n"
"    font-weight: 600;\n"
"    background: #fff;\n"
"    padding: 0 16px;\n"
"}\n"
"#tableUserContainer{\n"
"    border: none;\n"
"    border-radius:  4px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"       padding: 0 16px;\n"
"    vertical-align: middle;\n"
"    height: 50px;\n"
"    border-bottom: 1px solid #ddd;    \n"
"    border-right: 1px solid #ddd;\n"
"}\n"
"\n"
"#stackedWidget{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#userDialogForm QLabel{\n"
"    color: #000;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#userDialogForm  QLineEdit, #userDialogForm QComboBox, QSpinBox{\n"
"    border: 1px solid #e0e5e9;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QLineEdit, QComboxBox,QSpinBox{\n"
"    border: 1px solid #e0e5e9;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus, #centralwidget QComboBox:focus, QSpinBox:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"#btnCancelUser,#btn_image_product, #btn_manufacture_date_product{\n"
"    background: #ebebeb;\n"
"    outline: none;\n"
"    border: 1px solid #e0e0e0;\n"
"    min-height: 36px;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btnCancelUser:hover, #btn_image_product:hover{\n"
"    background: #f4f5f8;\n"
"}\n"
"\n"
"#btnUser{\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-height: 36px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btnUser:hover{\n"
"        background: #0062cc;\n"
"}\n"
"\n"
"#footerUserContainer{\n"
"     background-color: #fbfbfe;\n"
"    padding: 12px 24px;\n"
"    border-top: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#backBtn{\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"#dialogTitleUser{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#popupHeader{\n"
"    height: 60px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"#widget_12, #widget_11, #widget_10, #widget_7, #confirmContainer, #widget_2, #widget_12{\n"
"        border-bottom: 1px solid #e0e0e0;\n"
"}    \n"
"\n"
"#userDialogForm{\n"
"        border-radius: 4px;\n"
"        border: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"\n"
"\n"
"#userDialogFormSubContainer{\n"
"    background: #e9e9e9;\n"
"    border-radius: 4px;\n"
"}\n"
" #formInput_4 QLabel {\n"
"    margin-top: 10px;\n"
"}\n"
"QHBoxLayout QLabel{\n"
"    background: red;\n"
"}\n"
"\n"
"#label_product_1, #labelUserName, #labelPassword, #labelConfirm{\n"
"    margin-top:30px;\n"
"}\n"
"\n"
"QPushButton, QComboBox{\n"
"    min-width: 80px;\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#error_product_image, #error_quantity, #error_manufacture_date, #error_description, #error_price, #error_category, #error_product_name, #error_product_code{\n"
"    padding-top: 8px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"#addUserBtn, #btn_add_category, #btn_add_product{\n"
"        width:  100px;\n"
"        background: #2979ff;\n"
"        color: #fff;\n"
"}\n"
"\n"
"#addUserBtn:hover{\n"
"    background: #1a73e8;\n"
"}\n"
"\n"
"#addUserBtn QLabel{\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#search_btn_2{\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer QLineEdit, #searchBoxContainer_2 QLineEdit, #search_input_category_2, #search_input_product_2{\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer, #searchBoxContainer_3,#searchBoxContainer_4{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;    \n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#searchBoxContainer_2{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#headerAdmin{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#change_btn{\n"
"    max-width: 20px !important;\n"
"}\n"
"\n"
"#change_btn:hover{\n"
"    background: #ddd;\n"
"}\n"
"\n"
"#change_btn, #search_btn_5,  #search_btn_2, #back_btn_category, #search_btn_category_2, #search_btn_product_2, #btn_image_product, #btn_manufacture_date_product, #back_btn_product{\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"\n"
"#search_input_5{\n"
"    padding: 0;\n"
"    padding-left: 10px\n"
"}\n"
"\n"
"#customers_btn_2, #products_btn_2, #orders_btn_2, #dashboard_btn_2,#home_btn_2,#user_btn_2, #category_btn_2{\n"
"    text-align: left;\n"
"}\n"
"\n"
"#label_required_4, #label_required_3, #label_required_2, #label_required_1{\n"
"    text-align: right;\n"
"}\n"
"\n"
"#btn_image_product{\n"
"    min-height:  40px;\n"
"    min-width: 64px;\n"
"}\n"
"\n"
"QPlainTextEdit{\n"
"    min-height: 82px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.popupHeader = QtWidgets.QWidget(self.widget_6)
        self.popupHeader.setMinimumSize(QtCore.QSize(0, 60))
        self.popupHeader.setObjectName("popupHeader")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.popupHeader)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.back_btn_product = QtWidgets.QPushButton(self.popupHeader)
        self.back_btn_product.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn_product.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/icon/back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn_product.setIcon(icon)
        self.back_btn_product.setObjectName("back_btn_product")
        self.horizontalLayout_7.addWidget(self.back_btn_product)
        self.dialog_product_title = QtWidgets.QLabel(self.popupHeader)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(True)
        self.dialog_product_title.setFont(font)
        self.dialog_product_title.setObjectName("dialog_product_title")
        self.horizontalLayout_7.addWidget(self.dialog_product_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addWidget(self.popupHeader)
        self.widget_9 = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.userDialogForm = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userDialogForm.sizePolicy().hasHeightForWidth())
        self.userDialogForm.setSizePolicy(sizePolicy)
        self.userDialogForm.setMinimumSize(QtCore.QSize(900, 300))
        self.userDialogForm.setObjectName("userDialogForm")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.userDialogForm)
        self.verticalLayout_10.setContentsMargins(50, 20, 50, 30)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.userDialogForm)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -45, 783, 961))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 105))
        self.widget_7.setObjectName("widget_7")
        self.widget_27 = QtWidgets.QWidget(self.widget_7)
        self.widget_27.setGeometry(QtCore.QRect(0, 0, 747, 105))
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.formInput_11 = QtWidgets.QHBoxLayout()
        self.formInput_11.setContentsMargins(-1, 0, -1, -1)
        self.formInput_11.setSpacing(0)
        self.formInput_11.setObjectName("formInput_11")
        self.label_product_2 = QtWidgets.QWidget(self.widget_27)
        self.label_product_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_2.setObjectName("label_product_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.label_product_2)
        self.horizontalLayout_9.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.label_product_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.label_required_5 = QtWidgets.QLabel(self.label_product_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_5.sizePolicy().hasHeightForWidth())
        self.label_required_5.setSizePolicy(sizePolicy)
        self.label_required_5.setObjectName("label_required_5")
        self.horizontalLayout_9.addWidget(self.label_required_5)
        self.formInput_11.addWidget(self.label_product_2, 0, QtCore.Qt.AlignTop)
        self.widget_28 = QtWidgets.QWidget(self.widget_27)
        self.widget_28.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_28)
        self.verticalLayout_20.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.product_code_le = QtWidgets.QLineEdit(self.widget_28)
        self.product_code_le.setMinimumSize(QtCore.QSize(222, 46))
        self.product_code_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.product_code_le.setFont(font)
        self.product_code_le.setText("")
        self.product_code_le.setClearButtonEnabled(True)
        self.product_code_le.setObjectName("product_code_le")
        self.verticalLayout_20.addWidget(self.product_code_le)
        self.error_product_code = QtWidgets.QLabel(self.widget_28)
        self.error_product_code.setText("")
        self.error_product_code.setObjectName("error_product_code")
        self.verticalLayout_20.addWidget(self.error_product_code)
        self.formInput_11.addWidget(self.widget_28, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_29.addLayout(self.formInput_11)
        self.verticalLayout_21.addWidget(self.widget_7)
        self.widget_26 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_26.sizePolicy().hasHeightForWidth())
        self.widget_26.setSizePolicy(sizePolicy)
        self.widget_26.setMinimumSize(QtCore.QSize(0, 105))
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_14 = QtWidgets.QWidget(self.widget_26)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.formInput_5 = QtWidgets.QHBoxLayout()
        self.formInput_5.setContentsMargins(-1, 0, -1, -1)
        self.formInput_5.setSpacing(0)
        self.formInput_5.setObjectName("formInput_5")
        self.label_product_1 = QtWidgets.QWidget(self.widget_14)
        self.label_product_1.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_1.setObjectName("label_product_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.label_product_1)
        self.horizontalLayout_2.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.label_product_1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_required_1 = QtWidgets.QLabel(self.label_product_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_1.sizePolicy().hasHeightForWidth())
        self.label_required_1.setSizePolicy(sizePolicy)
        self.label_required_1.setObjectName("label_required_1")
        self.horizontalLayout_2.addWidget(self.label_required_1)
        self.formInput_5.addWidget(self.label_product_1, 0, QtCore.Qt.AlignTop)
        self.widget_15 = QtWidgets.QWidget(self.widget_14)
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_16.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.product_name_le = QtWidgets.QLineEdit(self.widget_15)
        self.product_name_le.setMinimumSize(QtCore.QSize(222, 46))
        self.product_name_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.product_name_le.setFont(font)
        self.product_name_le.setText("")
        self.product_name_le.setPlaceholderText("Tên sản phẩm")
        self.product_name_le.setClearButtonEnabled(True)
        self.product_name_le.setObjectName("product_name_le")
        self.verticalLayout_16.addWidget(self.product_name_le)
        self.error_product_name = QtWidgets.QLabel(self.widget_15)
        self.error_product_name.setText("")
        self.error_product_name.setObjectName("error_product_name")
        self.verticalLayout_16.addWidget(self.error_product_name)
        self.formInput_5.addWidget(self.widget_15, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_20.addLayout(self.formInput_5)
        self.verticalLayout_12.addWidget(self.widget_14)
        self.verticalLayout_21.addWidget(self.widget_26)
        self.widget_10 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 105))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_3 = QtWidgets.QWidget(self.widget_10)
        self.widget_3.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        self.widget_3.setFont(font)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_required_2 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_2.sizePolicy().hasHeightForWidth())
        self.label_required_2.setSizePolicy(sizePolicy)
        self.label_required_2.setObjectName("label_required_2")
        self.horizontalLayout_3.addWidget(self.label_required_2)
        self.horizontalLayout_13.addWidget(self.widget_3, 0, QtCore.Qt.AlignTop)
        self.formInput_6 = QtWidgets.QWidget(self.widget_10)
        self.formInput_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formInput_6.setObjectName("formInput_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.formInput_6)
        self.verticalLayout_13.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_24 = QtWidgets.QWidget(self.formInput_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_24.sizePolicy().hasHeightForWidth())
        self.widget_24.setSizePolicy(sizePolicy)
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_24)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.category_le = QtWidgets.QComboBox(self.widget_24)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.category_le.setFont(font)
        self.category_le.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.category_le.setEditable(False)
        self.category_le.setCurrentText("")
        self.category_le.setModelColumn(0)
        self.category_le.setObjectName("category_le")
        self.category_le.addItem("")
        self.horizontalLayout.addWidget(self.category_le)
        self.btn_add_product_category = QtWidgets.QPushButton(self.widget_24)
        self.btn_add_product_category.setMinimumSize(QtCore.QSize(54, 46))
        self.btn_add_product_category.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.btn_add_product_category.setFont(font)
        self.btn_add_product_category.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_add_product_category.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/resources/icon/plus-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_product_category.setIcon(icon1)
        self.btn_add_product_category.setObjectName("btn_add_product_category")
        self.horizontalLayout.addWidget(self.btn_add_product_category)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_13.addWidget(self.widget_24)
        self.error_category = QtWidgets.QLabel(self.formInput_6)
        self.error_category.setText("")
        self.error_category.setObjectName("error_category")
        self.verticalLayout_13.addWidget(self.error_category, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_13.addWidget(self.formInput_6, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.verticalLayout_21.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 105))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 105))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_4 = QtWidgets.QWidget(self.widget_11)
        self.widget_4.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_required_3 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_3.sizePolicy().hasHeightForWidth())
        self.label_required_3.setSizePolicy(sizePolicy)
        self.label_required_3.setObjectName("label_required_3")
        self.horizontalLayout_4.addWidget(self.label_required_3)
        self.horizontalLayout_15.addWidget(self.widget_4, 0, QtCore.Qt.AlignTop)
        self.formInput_7 = QtWidgets.QWidget(self.widget_11)
        self.formInput_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formInput_7.setObjectName("formInput_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.formInput_7)
        self.verticalLayout_14.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_24.setSpacing(15)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.product_image_le = QtWidgets.QLineEdit(self.formInput_7)
        self.product_image_le.setReadOnly(True)
        self.product_image_le.setObjectName("product_image_le")
        self.horizontalLayout_24.addWidget(self.product_image_le)
        self.btn_image_product = QtWidgets.QPushButton(self.formInput_7)
        self.btn_image_product.setMinimumSize(QtCore.QSize(56, 46))
        self.btn_image_product.setMaximumSize(QtCore.QSize(46, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.btn_image_product.setFont(font)
        self.btn_image_product.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_image_product.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/resources/icon/multiple-images.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_image_product.setIcon(icon2)
        self.btn_image_product.setIconSize(QtCore.QSize(24, 24))
        self.btn_image_product.setObjectName("btn_image_product")
        self.horizontalLayout_24.addWidget(self.btn_image_product)
        self.verticalLayout_14.addLayout(self.horizontalLayout_24)
        self.error_product_image = QtWidgets.QLabel(self.formInput_7)
        self.error_product_image.setText("")
        self.error_product_image.setObjectName("error_product_image")
        self.verticalLayout_14.addWidget(self.error_product_image, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_15.addWidget(self.formInput_7, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.verticalLayout_21.addWidget(self.widget_11)
        self.confirmContainer = QtWidgets.QWidget(self.widget)
        self.confirmContainer.setMinimumSize(QtCore.QSize(0, 105))
        self.confirmContainer.setObjectName("confirmContainer")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.confirmContainer)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.widget_5 = QtWidgets.QWidget(self.confirmContainer)
        self.widget_5.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_required_4 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_4.sizePolicy().hasHeightForWidth())
        self.label_required_4.setSizePolicy(sizePolicy)
        self.label_required_4.setObjectName("label_required_4")
        self.horizontalLayout_5.addWidget(self.label_required_4)
        self.horizontalLayout_17.addWidget(self.widget_5, 0, QtCore.Qt.AlignTop)
        self.formInput_3 = QtWidgets.QWidget(self.confirmContainer)
        self.formInput_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formInput_3.setObjectName("formInput_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.formInput_3)
        self.verticalLayout_15.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.price_le = QtWidgets.QSpinBox(self.formInput_3)
        self.price_le.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.price_le.setMaximum(1000000000)
        self.price_le.setObjectName("price_le")
        self.verticalLayout_15.addWidget(self.price_le)
        self.error_price = QtWidgets.QLabel(self.formInput_3)
        self.error_price.setText("")
        self.error_price.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.error_price.setObjectName("error_price")
        self.verticalLayout_15.addWidget(self.error_price, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_17.addWidget(self.formInput_3, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        self.verticalLayout_21.addWidget(self.confirmContainer)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 105))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_16 = QtWidgets.QWidget(self.widget_2)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.formInput_8 = QtWidgets.QHBoxLayout()
        self.formInput_8.setContentsMargins(-1, 0, -1, -1)
        self.formInput_8.setSpacing(0)
        self.formInput_8.setObjectName("formInput_8")
        self.widget_8 = QtWidgets.QWidget(self.widget_16)
        self.widget_8.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.widget_8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.formInput_8.addWidget(self.widget_8, 0, QtCore.Qt.AlignTop)
        self.widget_17 = QtWidgets.QWidget(self.widget_16)
        self.widget_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_17.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.quantity_le = QtWidgets.QSpinBox(self.widget_17)
        self.quantity_le.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.quantity_le.setMaximum(1000000)
        self.quantity_le.setObjectName("quantity_le")
        self.verticalLayout_17.addWidget(self.quantity_le)
        self.error_quantity = QtWidgets.QLabel(self.widget_17)
        self.error_quantity.setText("")
        self.error_quantity.setObjectName("error_quantity")
        self.verticalLayout_17.addWidget(self.error_quantity)
        self.formInput_8.addWidget(self.widget_17, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_21.addLayout(self.formInput_8)
        self.verticalLayout_4.addWidget(self.widget_16)
        self.verticalLayout_21.addWidget(self.widget_2)
        self.widget_12 = QtWidgets.QWidget(self.widget)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 105))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.widget_18 = QtWidgets.QWidget(self.widget_12)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.formInput_9 = QtWidgets.QHBoxLayout()
        self.formInput_9.setContentsMargins(-1, 0, -1, -1)
        self.formInput_9.setSpacing(0)
        self.formInput_9.setObjectName("formInput_9")
        self.widget_13 = QtWidgets.QWidget(self.widget_18)
        self.widget_13.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_13.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_10.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.widget_13)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.formInput_9.addWidget(self.widget_13, 0, QtCore.Qt.AlignTop)
        self.widget_19 = QtWidgets.QWidget(self.widget_18)
        self.widget_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_18.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_25 = QtWidgets.QWidget(self.widget_19)
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_28.setSpacing(15)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.manufacture_date_le = QtWidgets.QLineEdit(self.widget_25)
        self.manufacture_date_le.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manufacture_date_le.setReadOnly(True)
        self.manufacture_date_le.setObjectName("manufacture_date_le")
        self.horizontalLayout_28.addWidget(self.manufacture_date_le)
        self.btn_manufacture_date_product = QtWidgets.QPushButton(self.widget_25)
        self.btn_manufacture_date_product.setMinimumSize(QtCore.QSize(56, 42))
        self.btn_manufacture_date_product.setMaximumSize(QtCore.QSize(46, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.btn_manufacture_date_product.setFont(font)
        self.btn_manufacture_date_product.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_manufacture_date_product.setText("")
        self.btn_manufacture_date_product.setIcon(icon2)
        self.btn_manufacture_date_product.setIconSize(QtCore.QSize(24, 24))
        self.btn_manufacture_date_product.setObjectName("btn_manufacture_date_product")
        self.horizontalLayout_28.addWidget(self.btn_manufacture_date_product)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.verticalLayout_18.addWidget(self.widget_25)
        self.error_manufacture_date = QtWidgets.QLabel(self.widget_19)
        self.error_manufacture_date.setText("")
        self.error_manufacture_date.setObjectName("error_manufacture_date")
        self.verticalLayout_18.addWidget(self.error_manufacture_date)
        self.formInput_9.addWidget(self.widget_19, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_22.addLayout(self.formInput_9)
        self.horizontalLayout_23.addWidget(self.widget_18)
        self.verticalLayout_21.addWidget(self.widget_12)
        self.widget_20 = QtWidgets.QWidget(self.widget)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.widget_21 = QtWidgets.QWidget(self.widget_20)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.formInput_10 = QtWidgets.QHBoxLayout()
        self.formInput_10.setContentsMargins(-1, 0, -1, -1)
        self.formInput_10.setSpacing(0)
        self.formInput_10.setObjectName("formInput_10")
        self.widget_22 = QtWidgets.QWidget(self.widget_21)
        self.widget_22.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_22.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_26.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_13 = QtWidgets.QLabel(self.widget_22)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_26.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_26.addWidget(self.label_14)
        self.formInput_10.addWidget(self.widget_22, 0, QtCore.Qt.AlignTop)
        self.widget_23 = QtWidgets.QWidget(self.widget_21)
        self.widget_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_19.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.description_le = QtWidgets.QPlainTextEdit(self.widget_23)
        self.description_le.setMinimumSize(QtCore.QSize(222, 94))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.description_le.setFont(font)
        self.description_le.setObjectName("description_le")
        self.verticalLayout_19.addWidget(self.description_le)
        self.error_description = QtWidgets.QLabel(self.widget_23)
        self.error_description.setText("")
        self.error_description.setObjectName("error_description")
        self.verticalLayout_19.addWidget(self.error_description)
        self.formInput_10.addWidget(self.widget_23, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_25.addLayout(self.formInput_10)
        self.horizontalLayout_27.addWidget(self.widget_21)
        self.verticalLayout_21.addWidget(self.widget_20)
        self.verticalLayout_5.addWidget(self.widget)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.userDialogFormSubContainer = QtWidgets.QWidget(self.userDialogForm)
        self.userDialogFormSubContainer.setObjectName("userDialogFormSubContainer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.userDialogFormSubContainer)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 10, 20, 10)
        self.horizontalLayout_19.setSpacing(10)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem2)
        self.btn_cancel_product = QtWidgets.QPushButton(self.userDialogFormSubContainer)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.btn_cancel_product.setFont(font)
        self.btn_cancel_product.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel_product.setObjectName("btn_cancel_product")
        self.horizontalLayout_19.addWidget(self.btn_cancel_product)
        self.btn_save_product = QtWidgets.QPushButton(self.userDialogFormSubContainer)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.btn_save_product.setFont(font)
        self.btn_save_product.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_product.setObjectName("btn_save_product")
        self.horizontalLayout_19.addWidget(self.btn_save_product)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.verticalLayout_6.addWidget(self.userDialogFormSubContainer)
        self.verticalLayout_10.addLayout(self.verticalLayout_6)
        self.horizontalLayout_11.addWidget(self.userDialogForm)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7.addWidget(self.widget_9)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addWidget(self.widget_6)
        self.verticalLayout.addLayout(self.verticalLayout_8)

        self.retranslateUi(Form)
        self.category_le.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dialog_product_title.setText(_translate("Form", "Thêm mới sản phẩm"))
        self.label_4.setText(_translate("Form", "Mã sản phẩm"))
        self.label_required_5.setText(_translate("Form", " *"))
        self.product_code_le.setPlaceholderText(_translate("Form", "Mã sản phẩm"))
        self.label_2.setText(_translate("Form", "Tên sản phẩm"))
        self.label_required_1.setText(_translate("Form", " *"))
        self.label_3.setText(_translate("Form", "Loại sản phẩm"))
        self.label_required_2.setText(_translate("Form", " *"))
        self.category_le.setPlaceholderText(_translate("Form", "Loại sản phẩm"))
        self.category_le.setItemText(0, _translate("Form", "Không có dữ liệu"))
        self.btn_add_product_category.setToolTip(_translate("Form", "Thêm loại sản phẩm"))
        self.label_5.setText(_translate("Form", "Hình ảnh"))
        self.label_required_3.setText(_translate("Form", " *"))
        self.product_image_le.setPlaceholderText(_translate("Form", "Không có hình ảnh nào"))
        self.label_7.setText(_translate("Form", "Giá"))
        self.label_required_4.setText(_translate("Form", " *"))
        self.label_9.setText(_translate("Form", "Số lượng"))
        self.label_10.setText(_translate("Form", " *"))
        self.label_11.setText(_translate("Form", "Ngày sản xuất"))
        self.label_12.setText(_translate("Form", " *"))
        self.manufacture_date_le.setPlaceholderText(_translate("Form", "Ngày sản xuất"))
        self.label_13.setText(_translate("Form", "Mô tả"))
        self.description_le.setPlaceholderText(_translate("Form", "Nhập mô tả"))
        self.btn_cancel_product.setText(_translate("Form", "Hủy"))
        self.btn_save_product.setText(_translate("Form", "Lưu"))
import ui.resource_rc
