# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/admin/supplier_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(924, 726)
        Form.setStyleSheet("QLineEdit, QPlainTextEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"      height: 48px;\n"
"    font-weight: 600;\n"
"    text-align: left;\n"
"    font-size: 14px;\n"
"\n"
"    font-weight: 600;\n"
"    background: #fff;\n"
"    padding: 0 16px;\n"
"}\n"
"#tableUserContainer{\n"
"    border: none;\n"
"    border-radius:  4px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"       padding: 0 16px;\n"
"    vertical-align: middle;\n"
"    height: 50px;\n"
"    border-bottom: 1px solid #ddd;    \n"
"    border-right: 1px solid #ddd;\n"
"    cursor: pointer;\n"
"}\n"
"    QScrollBar:vertical\n"
"    {\n"
"        background-color: #fff;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: #cdd3d6;         /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"#scrollArea_2, #verticalLayout_6, #userDialogForm, #scrollAreaWidgetContents_2, #widget{\n"
"    background: #fff;\n"
"}\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"#dialog_product_title{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus, QPlainTextEdit:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"#userDialogForm QLabel{\n"
"    color: #000;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#userDialogForm  QLineEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-height: 36px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"QHBoxLayout QLabel{\n"
"    background: red;\n"
"}\n"
"\n"
"#btn_save_supplier{\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"#btn_add_product_category{\n"
"    min-height: 42px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"#btn_save_supplier:hover{\n"
"        background: #0062cc;\n"
"}\n"
"\n"
"\n"
"#btn_cancel_supplier{\n"
"    background: #ebebeb;\n"
"    outline: none;\n"
"    border: 1px solid #e0e0e0;\n"
"    min-height: 36px;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btn_cancel_supplier:hover{\n"
"    background: #f4f5f8;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"      height: 48px;\n"
"    font-weight: 600;\n"
"    text-align: left;\n"
"    font-size: 14px;\n"
"\n"
"    font-weight: 600;\n"
"    background: #fff;\n"
"    padding: 0 16px;\n"
"}\n"
"#tableUserContainer{\n"
"    border: none;\n"
"    border-radius:  4px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"       padding: 0 16px;\n"
"    vertical-align: middle;\n"
"    height: 50px;\n"
"    border-bottom: 1px solid #ddd;\n"
"    border-right: 1px solid #ddd;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"#stackedWidget{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#userDialogForm QLabel{\n"
"    color: #000;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#userDialogForm  QLineEdit, #userDialogForm QComboBox, QSpinBox{\n"
"    border: 1px solid #e0e5e9;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QLineEdit, QComboxBox,QSpinBox{\n"
"    border: 1px solid #e0e5e9;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus, #centralwidget QComboBox:focus, QSpinBox:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"#btnCancelUser,#btn_image_product, #btn_manufacture_date_product{\n"
"    background: #ebebeb;\n"
"    outline: none;\n"
"    border: 1px solid #e0e0e0;\n"
"    min-height: 36px;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btnCancelUser:hover, #btn_image_product:hover{\n"
"    background: #f4f5f8;\n"
"}\n"
"\n"
"#btnUser{\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-height: 36px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btnUser:hover{\n"
"        background: #0062cc;\n"
"}\n"
"\n"
"#footerUserContainer{\n"
"     background-color: #fbfbfe;\n"
"    padding: 12px 24px;\n"
"    border-top: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#backBtn{\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"#dialog_supplier_title{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#popupHeader{\n"
"    height: 60px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"#widget_12, #widget_26, #widget_7, #confirmContainer, #widget_12, #widget_3{\n"
"        border-bottom: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#widget_4{\n"
"    border-top: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#userDialogForm{\n"
"        border-radius: 4px;\n"
"        border: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"\n"
"\n"
"#userDialogFormSubContainer{\n"
"    background: #e9e9e9;\n"
"    border-radius: 4px;\n"
"}\n"
" #formInput_4 QLabel {\n"
"    margin-top: 10px;\n"
"}\n"
"QHBoxLayout QLabel{\n"
"    background: red;\n"
"}\n"
"\n"
"#label_product_1, #labelUserName, #labelPassword, #labelConfirm{\n"
"    margin-top:30px;\n"
"}\n"
"\n"
"QPushButton, QComboBox{\n"
"    min-width: 80px;\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#error_user, #error_quantity, #error_manufacture_date, #error_description, #error_address, #error_phone, #error_name, #error_code{\n"
"    padding-top: 8px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"#addUserBtn, #btn_add_category, #btn_add_product{\n"
"        width:  100px;\n"
"        background: #2979ff;\n"
"        color: #fff;\n"
"}\n"
"\n"
"#addUserBtn:hover{\n"
"    background: #1a73e8;\n"
"}\n"
"\n"
"#addUserBtn QLabel{\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#search_btn_2{\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer QLineEdit, #searchBoxContainer_2 QLineEdit, #search_input_category_2, #search_input_product_2{\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer, #searchBoxContainer_3, #searchBoxContainer_5{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#searchBoxContainer_2{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#headerAdmin{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#change_btn{\n"
"    max-width: 20px !important;\n"
"}\n"
"\n"
"#change_btn:hover{\n"
"    background: #ddd;\n"
"}\n"
"\n"
"#btn_add_order_user, #search_btn_5,  #search_btn_2, #back_btn_category, #search_btn_category_2, #search_btn_product_2, #btn_image_product, #btn_manufacture_date_product, #back_btn_supplier, #search_btn_order_2{\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"\n"
"#search_input_5{\n"
"    padding: 0;\n"
"    padding-left: 10px\n"
"}\n"
"\n"
"#customers_btn_2, #products_btn_2, #orders_btn_2, #dashboard_btn_2,#home_btn_2,#user_btn_2, #category_btn_2{\n"
"    text-align: left;\n"
"}\n"
"\n"
"#label_required_4, #label_required_3, #label_required_2, #label_required_1{\n"
"    text-align: right;\n"
"}\n"
"\n"
"#btn_image_product{\n"
"    min-height:  40px;\n"
"    min-width: 64px;\n"
"}\n"
"\n"
"QPlainTextEdit{\n"
"    min-height: 82px;\n"
"}\n"
"\n"
"#table_product_order:item{\n"
"    border:none;\n"
"}\n"
"\n"
"#table_product_order_container{\n"
"    border: 1px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 34px;\n"
"    min-width: 34px;\n"
"    max-width: 34px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"#total_price_main{\n"
"    margin-right: 20px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.popupHeader = QtWidgets.QWidget(self.widget)
        self.popupHeader.setMinimumSize(QtCore.QSize(0, 60))
        self.popupHeader.setObjectName("popupHeader")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.popupHeader)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.back_btn_supplier = QtWidgets.QPushButton(self.popupHeader)
        self.back_btn_supplier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn_supplier.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/icon/back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn_supplier.setIcon(icon)
        self.back_btn_supplier.setObjectName("back_btn_supplier")
        self.horizontalLayout_7.addWidget(self.back_btn_supplier)
        self.dialog_supplier_title = QtWidgets.QLabel(self.popupHeader)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(True)
        self.dialog_supplier_title.setFont(font)
        self.dialog_supplier_title.setObjectName("dialog_supplier_title")
        self.horizontalLayout_7.addWidget(self.dialog_supplier_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addWidget(self.popupHeader)
        self.widget_9 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.userDialogForm = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userDialogForm.sizePolicy().hasHeightForWidth())
        self.userDialogForm.setSizePolicy(sizePolicy)
        self.userDialogForm.setMinimumSize(QtCore.QSize(900, 300))
        self.userDialogForm.setObjectName("userDialogForm")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.userDialogForm)
        self.verticalLayout_10.setContentsMargins(50, 20, 50, 30)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.userDialogForm)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 798, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 105))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 105))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_27 = QtWidgets.QWidget(self.widget_7)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.formInput_11 = QtWidgets.QHBoxLayout()
        self.formInput_11.setContentsMargins(-1, 0, -1, -1)
        self.formInput_11.setSpacing(0)
        self.formInput_11.setObjectName("formInput_11")
        self.label_product_2 = QtWidgets.QWidget(self.widget_27)
        self.label_product_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_2.setObjectName("label_product_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.label_product_2)
        self.horizontalLayout_9.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.label_product_2)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.label_required_5 = QtWidgets.QLabel(self.label_product_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_5.sizePolicy().hasHeightForWidth())
        self.label_required_5.setSizePolicy(sizePolicy)
        self.label_required_5.setObjectName("label_required_5")
        self.horizontalLayout_9.addWidget(self.label_required_5)
        self.formInput_11.addWidget(self.label_product_2, 0, QtCore.Qt.AlignTop)
        self.widget_28 = QtWidgets.QWidget(self.widget_27)
        self.widget_28.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_28)
        self.verticalLayout_20.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.code_le = QtWidgets.QLineEdit(self.widget_28)
        self.code_le.setMinimumSize(QtCore.QSize(222, 46))
        self.code_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.code_le.setFont(font)
        self.code_le.setText("")
        self.code_le.setClearButtonEnabled(True)
        self.code_le.setObjectName("code_le")
        self.verticalLayout_20.addWidget(self.code_le)
        self.error_code = QtWidgets.QLabel(self.widget_28)
        self.error_code.setText("")
        self.error_code.setObjectName("error_code")
        self.verticalLayout_20.addWidget(self.error_code)
        self.formInput_11.addWidget(self.widget_28, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_29.addLayout(self.formInput_11)
        self.verticalLayout_3.addWidget(self.widget_27)
        self.verticalLayout_21.addWidget(self.widget_7)
        self.widget_26 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_26.sizePolicy().hasHeightForWidth())
        self.widget_26.setSizePolicy(sizePolicy)
        self.widget_26.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_26.setMaximumSize(QtCore.QSize(16777215, 105))
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_14 = QtWidgets.QWidget(self.widget_26)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.formInput_5 = QtWidgets.QHBoxLayout()
        self.formInput_5.setContentsMargins(-1, 0, -1, -1)
        self.formInput_5.setSpacing(0)
        self.formInput_5.setObjectName("formInput_5")
        self.label_product_1 = QtWidgets.QWidget(self.widget_14)
        self.label_product_1.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_1.setObjectName("label_product_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.label_product_1)
        self.horizontalLayout_2.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.label_product_1)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_required_1 = QtWidgets.QLabel(self.label_product_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_1.sizePolicy().hasHeightForWidth())
        self.label_required_1.setSizePolicy(sizePolicy)
        self.label_required_1.setObjectName("label_required_1")
        self.horizontalLayout_2.addWidget(self.label_required_1)
        self.formInput_5.addWidget(self.label_product_1, 0, QtCore.Qt.AlignTop)
        self.widget_15 = QtWidgets.QWidget(self.widget_14)
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_29 = QtWidgets.QWidget(self.widget_15)
        self.widget_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_29.setObjectName("widget_29")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_29)
        self.verticalLayout_22.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.name_le = QtWidgets.QLineEdit(self.widget_29)
        self.name_le.setMinimumSize(QtCore.QSize(222, 46))
        self.name_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.name_le.setFont(font)
        self.name_le.setText("")
        self.name_le.setClearButtonEnabled(True)
        self.name_le.setObjectName("name_le")
        self.verticalLayout_22.addWidget(self.name_le)
        self.error_name = QtWidgets.QLabel(self.widget_29)
        self.error_name.setText("")
        self.error_name.setObjectName("error_name")
        self.verticalLayout_22.addWidget(self.error_name)
        self.verticalLayout_16.addWidget(self.widget_29)
        self.formInput_5.addWidget(self.widget_15)
        self.horizontalLayout_14.addLayout(self.formInput_5)
        self.verticalLayout_12.addWidget(self.widget_14)
        self.verticalLayout_21.addWidget(self.widget_26)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 105))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_32 = QtWidgets.QWidget(self.widget_3)
        self.widget_32.setObjectName("widget_32")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.widget_32)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.formInput_13 = QtWidgets.QHBoxLayout()
        self.formInput_13.setContentsMargins(-1, 0, -1, -1)
        self.formInput_13.setSpacing(0)
        self.formInput_13.setObjectName("formInput_13")
        self.label_product_4 = QtWidgets.QWidget(self.widget_32)
        self.label_product_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_4.setObjectName("label_product_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.label_product_4)
        self.horizontalLayout_10.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.label_product_4)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.label_required_7 = QtWidgets.QLabel(self.label_product_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_7.sizePolicy().hasHeightForWidth())
        self.label_required_7.setSizePolicy(sizePolicy)
        self.label_required_7.setText("")
        self.label_required_7.setObjectName("label_required_7")
        self.horizontalLayout_10.addWidget(self.label_required_7)
        self.formInput_13.addWidget(self.label_product_4, 0, QtCore.Qt.AlignTop)
        self.widget_33 = QtWidgets.QWidget(self.widget_32)
        self.widget_33.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_33.setObjectName("widget_33")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_33)
        self.verticalLayout_24.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.phone_le = QtWidgets.QLineEdit(self.widget_33)
        self.phone_le.setMinimumSize(QtCore.QSize(222, 46))
        self.phone_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.phone_le.setFont(font)
        self.phone_le.setText("")
        self.phone_le.setClearButtonEnabled(True)
        self.phone_le.setObjectName("phone_le")
        self.verticalLayout_24.addWidget(self.phone_le)
        self.error_phone = QtWidgets.QLabel(self.widget_33)
        self.error_phone.setText("")
        self.error_phone.setObjectName("error_phone")
        self.verticalLayout_24.addWidget(self.error_phone)
        self.formInput_13.addWidget(self.widget_33, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_30.addLayout(self.formInput_13)
        self.verticalLayout_4.addWidget(self.widget_32)
        self.verticalLayout_21.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 105))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_30 = QtWidgets.QWidget(self.widget_5)
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.widget_30)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.formInput_12 = QtWidgets.QHBoxLayout()
        self.formInput_12.setContentsMargins(-1, 0, -1, -1)
        self.formInput_12.setSpacing(0)
        self.formInput_12.setObjectName("formInput_12")
        self.label_product_3 = QtWidgets.QWidget(self.widget_30)
        self.label_product_3.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_3.setObjectName("label_product_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.label_product_3)
        self.horizontalLayout_13.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.label_product_3)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.label_required_6 = QtWidgets.QLabel(self.label_product_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_6.sizePolicy().hasHeightForWidth())
        self.label_required_6.setSizePolicy(sizePolicy)
        self.label_required_6.setText("")
        self.label_required_6.setObjectName("label_required_6")
        self.horizontalLayout_13.addWidget(self.label_required_6)
        self.formInput_12.addWidget(self.label_product_3, 0, QtCore.Qt.AlignTop)
        self.widget_31 = QtWidgets.QWidget(self.widget_30)
        self.widget_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_31.setObjectName("widget_31")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_31)
        self.verticalLayout_23.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.address_le = QtWidgets.QLineEdit(self.widget_31)
        self.address_le.setObjectName("address_le")
        self.verticalLayout_23.addWidget(self.address_le)
        self.error_address = QtWidgets.QLabel(self.widget_31)
        self.error_address.setText("")
        self.error_address.setObjectName("error_address")
        self.verticalLayout_23.addWidget(self.error_address)
        self.formInput_12.addWidget(self.widget_31, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_31.addLayout(self.formInput_12)
        self.verticalLayout_17.addWidget(self.widget_30)
        self.verticalLayout_21.addWidget(self.widget_5)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.userDialogFormSubContainer = QtWidgets.QWidget(self.userDialogForm)
        self.userDialogFormSubContainer.setObjectName("userDialogFormSubContainer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.userDialogFormSubContainer)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 10, 20, 10)
        self.horizontalLayout_19.setSpacing(10)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem2)
        self.btn_cancel_supplier = QtWidgets.QPushButton(self.userDialogFormSubContainer)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.btn_cancel_supplier.setFont(font)
        self.btn_cancel_supplier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel_supplier.setObjectName("btn_cancel_supplier")
        self.horizontalLayout_19.addWidget(self.btn_cancel_supplier)
        self.btn_save_supplier = QtWidgets.QPushButton(self.userDialogFormSubContainer)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.btn_save_supplier.setFont(font)
        self.btn_save_supplier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_supplier.setObjectName("btn_save_supplier")
        self.horizontalLayout_19.addWidget(self.btn_save_supplier)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.verticalLayout_6.addWidget(self.userDialogFormSubContainer)
        self.verticalLayout_10.addLayout(self.verticalLayout_6)
        self.horizontalLayout_11.addWidget(self.userDialogForm)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7.addWidget(self.widget_9)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dialog_supplier_title.setText(_translate("Form", "Thêm mới nhà cung cấp"))
        self.label_4.setText(_translate("Form", "Mã đơn vị cung cấp"))
        self.label_required_5.setText(_translate("Form", " *"))
        self.code_le.setPlaceholderText(_translate("Form", "Mã đơn vị cung cấp"))
        self.label_2.setText(_translate("Form", "Tên đơn vị cung cấp"))
        self.label_required_1.setText(_translate("Form", " *"))
        self.name_le.setPlaceholderText(_translate("Form", "Tên đơn vị cung cấp"))
        self.label_6.setText(_translate("Form", "Số điện thoại liên hệ"))
        self.phone_le.setPlaceholderText(_translate("Form", "Số điện thoại"))
        self.label_5.setText(_translate("Form", "Địa chỉ"))
        self.address_le.setPlaceholderText(_translate("Form", "Địa chỉ"))
        self.btn_cancel_supplier.setText(_translate("Form", "Hủy"))
        self.btn_save_supplier.setText(_translate("Form", "Lưu"))
import ui.resource_rc
