# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/admin/user_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_user_form(object):
    def setupUi(self, user_form):
        user_form.setObjectName("user_form")
        user_form.resize(904, 664)
        user_form.setStyleSheet("QTableWidget QHeaderView::section {\n"
"      height: 48px;\n"
"    font-weight: 600;\n"
"    text-align: left;\n"
"    font-size: 14px;\n"
"\n"
"    font-weight: 600;\n"
"    background: #fff;\n"
"    padding: 0 16px;\n"
"}\n"
"#tableUserContainer{\n"
"    border: none;\n"
"    border-radius:  4px;\n"
"}\n"
"\n"
"#user_form, #user_form_container{\n"
"    background: #fff;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"       padding: 0 16px;\n"
"    vertical-align: middle;\n"
"    height: 50px;\n"
"    border-bottom: 1px solid #ddd;    \n"
"    border-right: 1px solid #ddd;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"#stackedWidget{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#userDialogForm QLabel{\n"
"    color: #000;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#userDialogForm  QLineEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"#btn_cancel_user{\n"
"    background: #ebebeb;\n"
"    outline: none;\n"
"    border: 1px solid #e0e0e0;\n"
"    min-height: 36px;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btn_cancel_user:hover{\n"
"    background: #f4f5f8;\n"
"}\n"
"\n"
"#btn_save_user{\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-height: 36px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btn_save_user:hover{\n"
"        background: #0062cc;\n"
"}\n"
"\n"
"#footerUserContainer{\n"
"     background-color: #fbfbfe;\n"
"    padding: 12px 24px;\n"
"    border-top: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#backBtn{\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"#dialogTitleUser{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#popupHeader{\n"
"    height: 60px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"#widget_12, #widget_11, #widget_10, #widget_7{\n"
"        border-bottom: 1px solid #e0e0e0;\n"
"}    \n"
"\n"
"#userDialogForm{\n"
"        border-radius: 4px;\n"
"        border: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"\n"
"\n"
"#userDialogFormSubContainer{\n"
"    background: #e9e9e9;\n"
"    border-radius: 4px;\n"
"}\n"
" #formInput_4 QLabel {\n"
"    margin-top: 10px;\n"
"}\n"
"QHBoxLayout QLabel{\n"
"    background: red;\n"
"}\n"
"\n"
"#labelName, #labelUserName, #labelPassword, #labelConfirm{\n"
"    margin-top:30px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-width: 80px;\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#error_name, #error_password, #error_username, #error_confirm{\n"
"    padding-top: 8px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"#addUserBtn, #btn_add_category, #btn_add_product, #btn_add_order, #btn_add_customer, #btn_add_user, #btn_add_rank{\n"
"        width:  100px;\n"
"        background: #2979ff;\n"
"        color: #fff;\n"
"}\n"
"\n"
"#addUserBtn:hover{\n"
"    background: #1a73e8;\n"
"}\n"
"\n"
"#addUserBtn QLabel{\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#search_btn_2{\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer QLineEdit, #searchBoxContainer_2 QLineEdit, #search_input_category_2, #search_input_product_2, #search_input_order, #search_input_customer, #search_input_rank{\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer, #searchBoxContainer_3,#searchBoxContainer_4, #searchBoxContainer_5, #searchBoxContainer_6, #searchBoxContainer_9{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;    \n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#searchBoxContainer_2{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#headerAdmin{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#change_btn{\n"
"    max-width: 20px !important;\n"
"}\n"
"\n"
"#change_btn:hover{\n"
"    background: #ddd;\n"
"}\n"
"\n"
"#change_btn, #search_btn_5,  #search_btn_2, #back_btn_user, #search_btn_category_2, #search_btn_product_2, #search_btn_order, #search_btn_customer, #search_btn_rank{\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"#search_input_5{\n"
"    padding: 0;\n"
"    padding-left: 10px\n"
"}\n"
"\n"
"#customers_btn_2, #products_btn_2, #orders_btn_2, #dashboard_btn_2,#home_btn_2,#user_btn_2, #category_btn_2, #rank_btn_2{\n"
"    text-align: left;\n"
"}\n"
"\n"
"QLineEdit, QPlainTextEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"      height: 48px;\n"
"    font-weight: 600;\n"
"    text-align: left;\n"
"    font-size: 14px;\n"
"\n"
"    font-weight: 600;\n"
"    background: #fff;\n"
"    padding: 0 16px;\n"
"}\n"
"#tableUserContainer{\n"
"    border: none;\n"
"    border-radius:  4px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"       padding: 0 16px;\n"
"    vertical-align: middle;\n"
"    height: 50px;\n"
"    border-bottom: 1px solid #ddd;    \n"
"    border-right: 1px solid #ddd;\n"
"    cursor: pointer;\n"
"}\n"
"    QScrollBar:vertical\n"
"    {\n"
"        background-color: #fff;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: #cdd3d6;         /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"#scrollArea_2, #verticalLayout_6, #userDialogForm, #scrollAreaWidgetContents_2, #widget{\n"
"    background: #fff;\n"
"}\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"#dialog_product_title{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus, QPlainTextEdit:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"#userDialogForm QLabel{\n"
"    color: #000;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#userDialogForm  QLineEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-height: 36px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"QHBoxLayout QLabel{\n"
"    background: red;\n"
"}\n"
"\n"
"#btn_save_order{\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"#btn_add_product_category{\n"
"    min-height: 42px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"#btn_save_order:hover{\n"
"        background: #0062cc;\n"
"}\n"
"\n"
"\n"
"#btn_cancel_order{\n"
"    background: #ebebeb;\n"
"    outline: none;\n"
"    border: 1px solid #e0e0e0;\n"
"    min-height: 36px;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btn_cancel_order:hover{\n"
"    background: #f4f5f8;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"      height: 48px;\n"
"    font-weight: 600;\n"
"    text-align: left;\n"
"    font-size: 14px;\n"
"\n"
"    font-weight: 600;\n"
"    background: #fff;\n"
"    padding: 0 16px;\n"
"}\n"
"#tableUserContainer{\n"
"    border: none;\n"
"    border-radius:  4px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"       padding: 0 16px;\n"
"    vertical-align: middle;\n"
"    height: 50px;\n"
"    border-bottom: 1px solid #ddd;\n"
"    border-right: 1px solid #ddd;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"#stackedWidget{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#userDialogForm QLabel{\n"
"    color: #000;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#userDialogForm  QLineEdit, #userDialogForm QComboBox, QSpinBox{\n"
"    border: 1px solid #e0e5e9;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QLineEdit, QComboxBox,QSpinBox{\n"
"    border: 1px solid #e0e5e9;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus, #centralwidget QComboBox:focus, QSpinBox:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"#btnCancelUser,#btn_image_product, #btn_manufacture_date_product{\n"
"    background: #ebebeb;\n"
"    outline: none;\n"
"    border: 1px solid #e0e0e0;\n"
"    min-height: 36px;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btnCancelUser:hover, #btn_image_product:hover{\n"
"    background: #f4f5f8;\n"
"}\n"
"\n"
"#btnUser{\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-height: 36px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btnUser:hover{\n"
"        background: #0062cc;\n"
"}\n"
"\n"
"#footerUserContainer{\n"
"     background-color: #fbfbfe;\n"
"    padding: 12px 24px;\n"
"    border-top: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#backBtn{\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"#dialogTitleUser{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#popupHeader{\n"
"    height: 60px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"#widget_12, #widget_10, #widget_7, #confirmContainer, #widget_12, #widget_26{\n"
"        border-bottom: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#widget_4{\n"
"    border-top: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#userDialogForm{\n"
"        border-radius: 4px;\n"
"        border: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"\n"
"\n"
"#userDialogFormSubContainer{\n"
"    background: #e9e9e9;\n"
"    border-radius: 4px;\n"
"}\n"
" #formInput_4 QLabel {\n"
"    margin-top: 10px;\n"
"}\n"
"QHBoxLayout QLabel{\n"
"    background: red;\n"
"}\n"
"\n"
"#label_product_1, #labelUserName, #labelPassword, #labelConfirm{\n"
"    margin-top:30px;\n"
"}\n"
"\n"
"QPushButton, QComboBox{\n"
"    min-width: 80px;\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#error_user, #error_quantity, #error_manufacture_date, #error_description, #error_price, #error_category, #error_order_code, #error_product_code{\n"
"    padding-top: 8px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"#addUserBtn, #btn_add_category, #btn_add_product{\n"
"        width:  100px;\n"
"        background: #2979ff;\n"
"        color: #fff;\n"
"}\n"
"\n"
"#addUserBtn:hover{\n"
"    background: #1a73e8;\n"
"}\n"
"\n"
"#addUserBtn QLabel{\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#search_btn_2{\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer QLineEdit, #searchBoxContainer_2 QLineEdit, #search_input_category_2, #search_input_product_2{\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer, #searchBoxContainer_3, #searchBoxContainer_5{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#searchBoxContainer_2{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#headerAdmin{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#change_btn{\n"
"    max-width: 20px !important;\n"
"}\n"
"\n"
"#change_btn:hover{\n"
"    background: #ddd;\n"
"}\n"
"\n"
"#btn_add_order_user, #search_btn_5,  #search_btn_2, #back_btn_category, #search_btn_category_2, #search_btn_product_2, #btn_image_product, #btn_manufacture_date_product, #back_btn_order, #search_btn_order_2{\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"\n"
"#search_input_5{\n"
"    padding: 0;\n"
"    padding-left: 10px\n"
"}\n"
"\n"
"#customers_btn_2, #products_btn_2, #orders_btn_2, #dashboard_btn_2,#home_btn_2,#user_btn_2, #category_btn_2{\n"
"    text-align: left;\n"
"}\n"
"\n"
"#label_required_4, #label_required_3, #label_required_2, #label_required_1{\n"
"    text-align: right;\n"
"}\n"
"\n"
"#btn_image_product{\n"
"    min-height:  40px;\n"
"    min-width: 64px;\n"
"}\n"
"\n"
"QPlainTextEdit{\n"
"    min-height: 82px;\n"
"}\n"
"\n"
"#table_product_order:item{\n"
"    border:none;\n"
"}\n"
"\n"
"#table_product_order_container{\n"
"    border: 1px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 34px;\n"
"    min-width: 34px;\n"
"    max-width: 34px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"#total_price_main{\n"
"    margin-right: 20px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(user_form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.user_form_container = QtWidgets.QWidget(user_form)
        self.user_form_container.setObjectName("user_form_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.user_form_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.popupHeader = QtWidgets.QWidget(self.user_form_container)
        self.popupHeader.setMinimumSize(QtCore.QSize(0, 60))
        self.popupHeader.setObjectName("popupHeader")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.popupHeader)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.back_btn_user = QtWidgets.QPushButton(self.popupHeader)
        self.back_btn_user.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn_user.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/icon/back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn_user.setIcon(icon)
        self.back_btn_user.setObjectName("back_btn_user")
        self.horizontalLayout_7.addWidget(self.back_btn_user)
        self.dialogTitleUser = QtWidgets.QLabel(self.popupHeader)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.dialogTitleUser.setFont(font)
        self.dialogTitleUser.setObjectName("dialogTitleUser")
        self.horizontalLayout_7.addWidget(self.dialogTitleUser)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addWidget(self.popupHeader)
        self.widget_9 = QtWidgets.QWidget(self.user_form_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.userDialogForm = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userDialogForm.sizePolicy().hasHeightForWidth())
        self.userDialogForm.setSizePolicy(sizePolicy)
        self.userDialogForm.setMinimumSize(QtCore.QSize(900, 300))
        self.userDialogForm.setObjectName("userDialogForm")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.userDialogForm)
        self.verticalLayout_10.setContentsMargins(50, 20, 50, 30)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.userDialogFormContainer_2 = QtWidgets.QVBoxLayout()
        self.userDialogFormContainer_2.setContentsMargins(0, 0, 0, 0)
        self.userDialogFormContainer_2.setSpacing(0)
        self.userDialogFormContainer_2.setObjectName("userDialogFormContainer_2")
        self.widget_7 = QtWidgets.QWidget(self.userDialogForm)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_14 = QtWidgets.QWidget(self.widget_7)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.formInput_5 = QtWidgets.QHBoxLayout()
        self.formInput_5.setContentsMargins(-1, 0, -1, -1)
        self.formInput_5.setSpacing(0)
        self.formInput_5.setObjectName("formInput_5")
        self.labelName = QtWidgets.QLabel(self.widget_14)
        self.labelName.setMinimumSize(QtCore.QSize(200, 0))
        self.labelName.setObjectName("labelName")
        self.formInput_5.addWidget(self.labelName, 0, QtCore.Qt.AlignTop)
        self.widget_15 = QtWidgets.QWidget(self.widget_14)
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_16.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.name_le = QtWidgets.QLineEdit(self.widget_15)
        self.name_le.setMinimumSize(QtCore.QSize(222, 46))
        self.name_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.name_le.setText("")
        self.name_le.setPlaceholderText("Họ và tên")
        self.name_le.setClearButtonEnabled(True)
        self.name_le.setObjectName("name_le")
        self.verticalLayout_16.addWidget(self.name_le)
        self.error_name = QtWidgets.QLabel(self.widget_15)
        self.error_name.setText("")
        self.error_name.setObjectName("error_name")
        self.verticalLayout_16.addWidget(self.error_name)
        self.formInput_5.addWidget(self.widget_15, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_20.addLayout(self.formInput_5)
        self.horizontalLayout_9.addWidget(self.widget_14)
        self.userDialogFormContainer_2.addWidget(self.widget_7)
        self.widget_10 = QtWidgets.QWidget(self.userDialogForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labelUserName = QtWidgets.QLabel(self.widget_10)
        self.labelUserName.setMinimumSize(QtCore.QSize(200, 0))
        self.labelUserName.setObjectName("labelUserName")
        self.horizontalLayout_13.addWidget(self.labelUserName, 0, QtCore.Qt.AlignTop)
        self.formInput_6 = QtWidgets.QWidget(self.widget_10)
        self.formInput_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formInput_6.setObjectName("formInput_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.formInput_6)
        self.verticalLayout_13.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.username_le = QtWidgets.QLineEdit(self.formInput_6)
        self.username_le.setMinimumSize(QtCore.QSize(222, 46))
        self.username_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.username_le.setClearButtonEnabled(True)
        self.username_le.setObjectName("username_le")
        self.verticalLayout_13.addWidget(self.username_le)
        self.error_username = QtWidgets.QLabel(self.formInput_6)
        self.error_username.setText("")
        self.error_username.setObjectName("error_username")
        self.verticalLayout_13.addWidget(self.error_username, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_13.addWidget(self.formInput_6, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.userDialogFormContainer_2.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.userDialogForm)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelPassword = QtWidgets.QLabel(self.widget_11)
        self.labelPassword.setMinimumSize(QtCore.QSize(200, 0))
        self.labelPassword.setObjectName("labelPassword")
        self.horizontalLayout_15.addWidget(self.labelPassword, 0, QtCore.Qt.AlignTop)
        self.formInput_7 = QtWidgets.QWidget(self.widget_11)
        self.formInput_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formInput_7.setObjectName("formInput_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.formInput_7)
        self.verticalLayout_14.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.password_le = QtWidgets.QLineEdit(self.formInput_7)
        self.password_le.setMinimumSize(QtCore.QSize(222, 46))
        self.password_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.password_le.setText("")
        self.password_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_le.setPlaceholderText("Mật khẩu")
        self.password_le.setClearButtonEnabled(True)
        self.password_le.setObjectName("password_le")
        self.verticalLayout_14.addWidget(self.password_le)
        self.error_password = QtWidgets.QLabel(self.formInput_7)
        self.error_password.setText("")
        self.error_password.setObjectName("error_password")
        self.verticalLayout_14.addWidget(self.error_password, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_15.addWidget(self.formInput_7, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.userDialogFormContainer_2.addWidget(self.widget_11)
        self.confirmContainer = QtWidgets.QWidget(self.userDialogForm)
        self.confirmContainer.setObjectName("confirmContainer")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.confirmContainer)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.labelConfirm = QtWidgets.QLabel(self.confirmContainer)
        self.labelConfirm.setMinimumSize(QtCore.QSize(200, 0))
        self.labelConfirm.setObjectName("labelConfirm")
        self.horizontalLayout_17.addWidget(self.labelConfirm, 0, QtCore.Qt.AlignTop)
        self.formInput_3 = QtWidgets.QWidget(self.confirmContainer)
        self.formInput_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formInput_3.setObjectName("formInput_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.formInput_3)
        self.verticalLayout_15.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.confirm_le = QtWidgets.QLineEdit(self.formInput_3)
        self.confirm_le.setMinimumSize(QtCore.QSize(222, 46))
        self.confirm_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.confirm_le.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.confirm_le.setText("")
        self.confirm_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_le.setClearButtonEnabled(True)
        self.confirm_le.setObjectName("confirm_le")
        self.verticalLayout_15.addWidget(self.confirm_le)
        self.error_confirm = QtWidgets.QLabel(self.formInput_3)
        self.error_confirm.setText("")
        self.error_confirm.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.error_confirm.setObjectName("error_confirm")
        self.verticalLayout_15.addWidget(self.error_confirm, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_17.addWidget(self.formInput_3, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        self.userDialogFormContainer_2.addWidget(self.confirmContainer)
        self.widget = QtWidgets.QWidget(self.userDialogForm)
        self.widget.setMinimumSize(QtCore.QSize(0, 105))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_30 = QtWidgets.QWidget(self.widget)
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.widget_30)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.formInput_12 = QtWidgets.QHBoxLayout()
        self.formInput_12.setContentsMargins(-1, 0, -1, -1)
        self.formInput_12.setSpacing(0)
        self.formInput_12.setObjectName("formInput_12")
        self.label_product_3 = QtWidgets.QWidget(self.widget_30)
        self.label_product_3.setMinimumSize(QtCore.QSize(200, 0))
        self.label_product_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_product_3.setObjectName("label_product_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.label_product_3)
        self.horizontalLayout_21.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_5 = QtWidgets.QLabel(self.label_product_3)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_21.addWidget(self.label_5)
        self.label_required_6 = QtWidgets.QLabel(self.label_product_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_required_6.sizePolicy().hasHeightForWidth())
        self.label_required_6.setSizePolicy(sizePolicy)
        self.label_required_6.setText("")
        self.label_required_6.setObjectName("label_required_6")
        self.horizontalLayout_21.addWidget(self.label_required_6)
        self.formInput_12.addWidget(self.label_product_3, 0, QtCore.Qt.AlignTop)
        self.widget_31 = QtWidgets.QWidget(self.widget_30)
        self.widget_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_31.setObjectName("widget_31")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_31)
        self.verticalLayout_23.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.level = QtWidgets.QComboBox(self.widget_31)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(-1)
        self.level.setFont(font)
        self.level.setObjectName("level")
        self.level.addItem("")
        self.level.addItem("")
        self.level.addItem("")
        self.verticalLayout_23.addWidget(self.level)
        self.error_order = QtWidgets.QLabel(self.widget_31)
        self.error_order.setText("")
        self.error_order.setObjectName("error_order")
        self.verticalLayout_23.addWidget(self.error_order)
        self.formInput_12.addWidget(self.widget_31, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_31.addLayout(self.formInput_12)
        self.verticalLayout_3.addWidget(self.widget_30)
        self.userDialogFormContainer_2.addWidget(self.widget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.userDialogFormContainer_2.addItem(spacerItem2)
        self.userDialogFormSubContainer = QtWidgets.QWidget(self.userDialogForm)
        self.userDialogFormSubContainer.setObjectName("userDialogFormSubContainer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.userDialogFormSubContainer)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 10, 20, 10)
        self.horizontalLayout_19.setSpacing(10)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem3)
        self.btn_cancel_user = QtWidgets.QPushButton(self.userDialogFormSubContainer)
        self.btn_cancel_user.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel_user.setObjectName("btn_cancel_user")
        self.horizontalLayout_19.addWidget(self.btn_cancel_user)
        self.btn_save_user = QtWidgets.QPushButton(self.userDialogFormSubContainer)
        self.btn_save_user.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save_user.setObjectName("btn_save_user")
        self.horizontalLayout_19.addWidget(self.btn_save_user)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.userDialogFormContainer_2.addWidget(self.userDialogFormSubContainer)
        self.verticalLayout_10.addLayout(self.userDialogFormContainer_2)
        self.horizontalLayout_11.addWidget(self.userDialogForm)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7.addWidget(self.widget_9)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addWidget(self.user_form_container)

        self.retranslateUi(user_form)
        QtCore.QMetaObject.connectSlotsByName(user_form)

    def retranslateUi(self, user_form):
        _translate = QtCore.QCoreApplication.translate
        user_form.setWindowTitle(_translate("user_form", "Form"))
        self.dialogTitleUser.setText(_translate("user_form", "Thêm mới tài khoản"))
        self.labelName.setText(_translate("user_form", "Họ và tên:"))
        self.labelUserName.setText(_translate("user_form", "Tài khoản:"))
        self.username_le.setPlaceholderText(_translate("user_form", "Email hoặc số điện thoại"))
        self.labelPassword.setText(_translate("user_form", "Mật khẩu:"))
        self.labelConfirm.setText(_translate("user_form", "Nhập lại mật khẩu"))
        self.confirm_le.setPlaceholderText(_translate("user_form", "Nhập lại mật khẩu"))
        self.label_5.setText(_translate("user_form", "Loại tài khoản"))
        self.level.setItemText(0, _translate("user_form", "Nhân viên"))
        self.level.setItemText(1, _translate("user_form", "Nhân viên kho"))
        self.level.setItemText(2, _translate("user_form", "Quản trị viên"))
        self.btn_cancel_user.setText(_translate("user_form", "Hủy"))
        self.btn_save_user.setText(_translate("user_form", "Lưu"))
import ui.resource_rc
